// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _graphene_euler_t {
 *     graphene_vec3_t __graphene_private_angles;
 *     graphene_euler_order_t __graphene_private_order;
 * };
 * }
 */
public class _graphene_euler_t {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4, Constants$root.C_FLOAT$LAYOUT).withName("__graphene_private_value")
        ).withName("__graphene_private_angles"),
        Constants$root.C_INT$LAYOUT.withName("__graphene_private_order"),
        MemoryLayout.paddingLayout(96)
    ).withName("_graphene_euler_t");
    public static MemoryLayout $LAYOUT() {
        return _graphene_euler_t.$struct$LAYOUT;
    }
    public static MemorySegment __graphene_private_angles$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    static final VarHandle __graphene_private_order$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__graphene_private_order"));
    public static VarHandle __graphene_private_order$VH() {
        return _graphene_euler_t.__graphene_private_order$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * graphene_euler_order_t __graphene_private_order;
     * }
     */
    public static int __graphene_private_order$get(MemorySegment seg) {
        return (int)_graphene_euler_t.__graphene_private_order$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * graphene_euler_order_t __graphene_private_order;
     * }
     */
    public static void __graphene_private_order$set(MemorySegment seg, int x) {
        _graphene_euler_t.__graphene_private_order$VH.set(seg, x);
    }
    public static int __graphene_private_order$get(MemorySegment seg, long index) {
        return (int)_graphene_euler_t.__graphene_private_order$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __graphene_private_order$set(MemorySegment seg, long index, int x) {
        _graphene_euler_t.__graphene_private_order$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


