// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _graphene_quaternion_t {
 *     float __graphene_private_x;
 *     float __graphene_private_y;
 *     float __graphene_private_z;
 *     float __graphene_private_w;
 * };
 * }
 */
public class _graphene_quaternion_t {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("__graphene_private_x"),
        Constants$root.C_FLOAT$LAYOUT.withName("__graphene_private_y"),
        Constants$root.C_FLOAT$LAYOUT.withName("__graphene_private_z"),
        Constants$root.C_FLOAT$LAYOUT.withName("__graphene_private_w")
    ).withName("_graphene_quaternion_t");
    public static MemoryLayout $LAYOUT() {
        return _graphene_quaternion_t.$struct$LAYOUT;
    }
    static final VarHandle __graphene_private_x$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__graphene_private_x"));
    public static VarHandle __graphene_private_x$VH() {
        return _graphene_quaternion_t.__graphene_private_x$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float __graphene_private_x;
     * }
     */
    public static float __graphene_private_x$get(MemorySegment seg) {
        return (float)_graphene_quaternion_t.__graphene_private_x$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float __graphene_private_x;
     * }
     */
    public static void __graphene_private_x$set(MemorySegment seg, float x) {
        _graphene_quaternion_t.__graphene_private_x$VH.set(seg, x);
    }
    public static float __graphene_private_x$get(MemorySegment seg, long index) {
        return (float)_graphene_quaternion_t.__graphene_private_x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __graphene_private_x$set(MemorySegment seg, long index, float x) {
        _graphene_quaternion_t.__graphene_private_x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __graphene_private_y$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__graphene_private_y"));
    public static VarHandle __graphene_private_y$VH() {
        return _graphene_quaternion_t.__graphene_private_y$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float __graphene_private_y;
     * }
     */
    public static float __graphene_private_y$get(MemorySegment seg) {
        return (float)_graphene_quaternion_t.__graphene_private_y$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float __graphene_private_y;
     * }
     */
    public static void __graphene_private_y$set(MemorySegment seg, float x) {
        _graphene_quaternion_t.__graphene_private_y$VH.set(seg, x);
    }
    public static float __graphene_private_y$get(MemorySegment seg, long index) {
        return (float)_graphene_quaternion_t.__graphene_private_y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __graphene_private_y$set(MemorySegment seg, long index, float x) {
        _graphene_quaternion_t.__graphene_private_y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __graphene_private_z$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__graphene_private_z"));
    public static VarHandle __graphene_private_z$VH() {
        return _graphene_quaternion_t.__graphene_private_z$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float __graphene_private_z;
     * }
     */
    public static float __graphene_private_z$get(MemorySegment seg) {
        return (float)_graphene_quaternion_t.__graphene_private_z$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float __graphene_private_z;
     * }
     */
    public static void __graphene_private_z$set(MemorySegment seg, float x) {
        _graphene_quaternion_t.__graphene_private_z$VH.set(seg, x);
    }
    public static float __graphene_private_z$get(MemorySegment seg, long index) {
        return (float)_graphene_quaternion_t.__graphene_private_z$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __graphene_private_z$set(MemorySegment seg, long index, float x) {
        _graphene_quaternion_t.__graphene_private_z$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __graphene_private_w$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__graphene_private_w"));
    public static VarHandle __graphene_private_w$VH() {
        return _graphene_quaternion_t.__graphene_private_w$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float __graphene_private_w;
     * }
     */
    public static float __graphene_private_w$get(MemorySegment seg) {
        return (float)_graphene_quaternion_t.__graphene_private_w$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float __graphene_private_w;
     * }
     */
    public static void __graphene_private_w$set(MemorySegment seg, float x) {
        _graphene_quaternion_t.__graphene_private_w$VH.set(seg, x);
    }
    public static float __graphene_private_w$get(MemorySegment seg, long index) {
        return (float)_graphene_quaternion_t.__graphene_private_w$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __graphene_private_w$set(MemorySegment seg, long index, float x) {
        _graphene_quaternion_t.__graphene_private_w$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


