// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _GtkTreeModelFilterClass {
 *     GObjectClass parent_class;
 *     gboolean (*visible)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*);
 *     void (*modify)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*,GValue*,int);
 *     gpointer padding[8];
 * };
 * }
 */
public class _GtkTreeModelFilterClass {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                Constants$root.C_LONG_LONG$LAYOUT.withName("g_type")
            ).withName("g_type_class"),
            Constants$root.C_POINTER$LAYOUT.withName("construct_properties"),
            Constants$root.C_POINTER$LAYOUT.withName("constructor"),
            Constants$root.C_POINTER$LAYOUT.withName("set_property"),
            Constants$root.C_POINTER$LAYOUT.withName("get_property"),
            Constants$root.C_POINTER$LAYOUT.withName("dispose"),
            Constants$root.C_POINTER$LAYOUT.withName("finalize"),
            Constants$root.C_POINTER$LAYOUT.withName("dispatch_properties_changed"),
            Constants$root.C_POINTER$LAYOUT.withName("notify"),
            Constants$root.C_POINTER$LAYOUT.withName("constructed"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("flags"),
            MemoryLayout.sequenceLayout(6, Constants$root.C_POINTER$LAYOUT).withName("pdummy")
        ).withName("parent_class"),
        Constants$root.C_POINTER$LAYOUT.withName("visible"),
        Constants$root.C_POINTER$LAYOUT.withName("modify"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_POINTER$LAYOUT).withName("padding")
    ).withName("_GtkTreeModelFilterClass");
    public static MemoryLayout $LAYOUT() {
        return _GtkTreeModelFilterClass.$struct$LAYOUT;
    }
    public static MemorySegment parent_class$slice(MemorySegment seg) {
        return seg.asSlice(0, 136);
    }
    static final FunctionDescriptor visible$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor visible_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle visible_UP$MH = RuntimeHelper.upcallHandle(visible.class, "apply", _GtkTreeModelFilterClass.visible_UP$FUNC);
    static final FunctionDescriptor visible_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle visible_DOWN$MH = RuntimeHelper.downcallHandle(
        _GtkTreeModelFilterClass.visible_DOWN$FUNC
    );
    /**
     * {@snippet :
 * gboolean (*visible)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*);
     * }
     */
    public interface visible {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
        static MemorySegment allocate(visible fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(_GtkTreeModelFilterClass.visible_UP$MH, fi, _GtkTreeModelFilterClass.visible$FUNC, scope);
        }
        static visible ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
                try {
                    return (int)_GtkTreeModelFilterClass.visible_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle visible$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("visible"));
    public static VarHandle visible$VH() {
        return _GtkTreeModelFilterClass.visible$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * gboolean (*visible)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*);
     * }
     */
    public static MemorySegment visible$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_GtkTreeModelFilterClass.visible$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * gboolean (*visible)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*);
     * }
     */
    public static void visible$set(MemorySegment seg, MemorySegment x) {
        _GtkTreeModelFilterClass.visible$VH.set(seg, x);
    }
    public static MemorySegment visible$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_GtkTreeModelFilterClass.visible$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void visible$set(MemorySegment seg, long index, MemorySegment x) {
        _GtkTreeModelFilterClass.visible$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static visible visible(MemorySegment segment, SegmentScope scope) {
        return visible.ofAddress(visible$get(segment), scope);
    }
    static final FunctionDescriptor modify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final FunctionDescriptor modify_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle modify_UP$MH = RuntimeHelper.upcallHandle(modify.class, "apply", _GtkTreeModelFilterClass.modify_UP$FUNC);
    static final FunctionDescriptor modify_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle modify_DOWN$MH = RuntimeHelper.downcallHandle(
        _GtkTreeModelFilterClass.modify_DOWN$FUNC
    );
    /**
     * {@snippet :
 * void (*modify)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*,GValue*,int);
     * }
     */
    public interface modify {

        void apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2, java.lang.foreign.MemorySegment _x3, int _x4);
        static MemorySegment allocate(modify fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(_GtkTreeModelFilterClass.modify_UP$MH, fi, _GtkTreeModelFilterClass.modify$FUNC, scope);
        }
        static modify ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2, java.lang.foreign.MemorySegment __x3, int __x4) -> {
                try {
                    _GtkTreeModelFilterClass.modify_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle modify$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("modify"));
    public static VarHandle modify$VH() {
        return _GtkTreeModelFilterClass.modify$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void (*modify)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*,GValue*,int);
     * }
     */
    public static MemorySegment modify$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_GtkTreeModelFilterClass.modify$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void (*modify)(GtkTreeModelFilter*,GtkTreeModel*,GtkTreeIter*,GValue*,int);
     * }
     */
    public static void modify$set(MemorySegment seg, MemorySegment x) {
        _GtkTreeModelFilterClass.modify$VH.set(seg, x);
    }
    public static MemorySegment modify$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_GtkTreeModelFilterClass.modify$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void modify$set(MemorySegment seg, long index, MemorySegment x) {
        _GtkTreeModelFilterClass.modify$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static modify modify(MemorySegment segment, SegmentScope scope) {
        return modify.ofAddress(modify$get(segment), scope);
    }
    public static MemorySegment padding$slice(MemorySegment seg) {
        return seg.asSlice(152, 64);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


