// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1085 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1085() {}
    static final FunctionDescriptor gdk_device_get_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_display$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_display",
        constants$1085.gdk_device_get_display$FUNC
    );
    static final FunctionDescriptor gdk_device_get_seat$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_seat$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_seat",
        constants$1085.gdk_device_get_seat$FUNC
    );
    static final FunctionDescriptor gdk_device_get_device_tool$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_device_tool$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_device_tool",
        constants$1085.gdk_device_get_device_tool$FUNC
    );
    static final FunctionDescriptor gdk_device_get_source$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_source$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_source",
        constants$1085.gdk_device_get_source$FUNC
    );
    static final FunctionDescriptor gdk_device_get_has_cursor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_has_cursor$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_has_cursor",
        constants$1085.gdk_device_get_has_cursor$FUNC
    );
    static final FunctionDescriptor gdk_device_get_num_touches$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_num_touches$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_num_touches",
        constants$1085.gdk_device_get_num_touches$FUNC
    );
}


