// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1981 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1981() {}
    static final MemorySegment GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("win32-driver-extra");
}


