// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1708 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1708() {}
    static final FunctionDescriptor gtk_media_stream_prepared$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_media_stream_prepared$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_prepared",
        constants$1708.gtk_media_stream_prepared$FUNC
    );
    static final FunctionDescriptor gtk_media_stream_unprepared$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_media_stream_unprepared$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_unprepared",
        constants$1708.gtk_media_stream_unprepared$FUNC
    );
    static final FunctionDescriptor gtk_media_stream_stream_prepared$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_media_stream_stream_prepared$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_stream_prepared",
        constants$1708.gtk_media_stream_stream_prepared$FUNC
    );
    static final FunctionDescriptor gtk_media_stream_stream_unprepared$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_media_stream_stream_unprepared$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_stream_unprepared",
        constants$1708.gtk_media_stream_stream_unprepared$FUNC
    );
    static final FunctionDescriptor gtk_media_stream_update$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_media_stream_update$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_update",
        constants$1708.gtk_media_stream_update$FUNC
    );
    static final FunctionDescriptor gtk_media_stream_ended$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_media_stream_ended$MH = RuntimeHelper.downcallHandle(
        "gtk_media_stream_ended",
        constants$1708.gtk_media_stream_ended$FUNC
    );
}


