// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1564 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1564() {}
    static final FunctionDescriptor gtk_icon_view_drop_position_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_icon_view_drop_position_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_drop_position_get_type",
        constants$1564.gtk_icon_view_drop_position_get_type$FUNC
    );
    static final FunctionDescriptor gtk_image_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_image_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_image_type_get_type",
        constants$1564.gtk_image_type_get_type$FUNC
    );
    static final FunctionDescriptor gtk_buttons_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_buttons_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_buttons_type_get_type",
        constants$1564.gtk_buttons_type_get_type$FUNC
    );
    static final FunctionDescriptor gtk_notebook_tab_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_notebook_tab_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_tab_get_type",
        constants$1564.gtk_notebook_tab_get_type$FUNC
    );
    static final FunctionDescriptor gtk_pad_action_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_pad_action_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_pad_action_type_get_type",
        constants$1564.gtk_pad_action_type_get_type$FUNC
    );
    static final FunctionDescriptor gtk_popover_menu_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_popover_menu_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_popover_menu_flags_get_type",
        constants$1564.gtk_popover_menu_flags_get_type$FUNC
    );
}


