// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1283 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1283() {}
    static final FunctionDescriptor gsk_radial_gradient_node_get_end$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_radial_gradient_node_get_end$MH = RuntimeHelper.downcallHandle(
        "gsk_radial_gradient_node_get_end",
        constants$1283.gsk_radial_gradient_node_get_end$FUNC
    );
    static final FunctionDescriptor gsk_repeating_radial_gradient_node_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gsk_repeating_radial_gradient_node_get_type$MH = RuntimeHelper.downcallHandle(
        "gsk_repeating_radial_gradient_node_get_type",
        constants$1283.gsk_repeating_radial_gradient_node_get_type$FUNC
    );
    static final FunctionDescriptor gsk_repeating_radial_gradient_node_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gsk_repeating_radial_gradient_node_new$MH = RuntimeHelper.downcallHandle(
        "gsk_repeating_radial_gradient_node_new",
        constants$1283.gsk_repeating_radial_gradient_node_new$FUNC
    );
    static final FunctionDescriptor gsk_border_node_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gsk_border_node_get_type$MH = RuntimeHelper.downcallHandle(
        "gsk_border_node_get_type",
        constants$1283.gsk_border_node_get_type$FUNC
    );
    static final FunctionDescriptor gsk_border_node_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_border_node_new$MH = RuntimeHelper.downcallHandle(
        "gsk_border_node_new",
        constants$1283.gsk_border_node_new$FUNC
    );
    static final FunctionDescriptor gsk_border_node_get_outline$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_border_node_get_outline$MH = RuntimeHelper.downcallHandle(
        "gsk_border_node_get_outline",
        constants$1283.gsk_border_node_get_outline$FUNC
    );
}


