// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1154() {}
    static final FunctionDescriptor ldexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ldexp$MH = RuntimeHelper.downcallHandle(
        "ldexp",
        constants$1154.ldexp$FUNC
    );
    static final FunctionDescriptor __ldexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __ldexp$MH = RuntimeHelper.downcallHandle(
        "__ldexp",
        constants$1154.__ldexp$FUNC
    );
    static final FunctionDescriptor log$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle log$MH = RuntimeHelper.downcallHandle(
        "log",
        constants$1154.log$FUNC
    );
    static final FunctionDescriptor __log$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __log$MH = RuntimeHelper.downcallHandle(
        "__log",
        constants$1154.__log$FUNC
    );
    static final FunctionDescriptor log10$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle log10$MH = RuntimeHelper.downcallHandle(
        "log10",
        constants$1154.log10$FUNC
    );
    static final FunctionDescriptor __log10$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __log10$MH = RuntimeHelper.downcallHandle(
        "__log10",
        constants$1154.__log10$FUNC
    );
}


