// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$180 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$180() {}
    static final FunctionDescriptor g_unichar_isalnum$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isalnum$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isalnum",
        constants$180.g_unichar_isalnum$FUNC
    );
    static final FunctionDescriptor g_unichar_isalpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isalpha$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isalpha",
        constants$180.g_unichar_isalpha$FUNC
    );
    static final FunctionDescriptor g_unichar_iscntrl$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_iscntrl$MH = RuntimeHelper.downcallHandle(
        "g_unichar_iscntrl",
        constants$180.g_unichar_iscntrl$FUNC
    );
    static final FunctionDescriptor g_unichar_isdigit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isdigit$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isdigit",
        constants$180.g_unichar_isdigit$FUNC
    );
    static final FunctionDescriptor g_unichar_isgraph$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isgraph$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isgraph",
        constants$180.g_unichar_isgraph$FUNC
    );
    static final FunctionDescriptor g_unichar_islower$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_islower$MH = RuntimeHelper.downcallHandle(
        "g_unichar_islower",
        constants$180.g_unichar_islower$FUNC
    );
}


