// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1245 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1245() {}
    static final FunctionDescriptor graphene_quaternion_init_from_radians$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle graphene_quaternion_init_from_radians$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_init_from_radians",
        constants$1245.graphene_quaternion_init_from_radians$FUNC
    );
    static final FunctionDescriptor graphene_quaternion_init_from_angle_vec3$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_quaternion_init_from_angle_vec3$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_init_from_angle_vec3",
        constants$1245.graphene_quaternion_init_from_angle_vec3$FUNC
    );
    static final FunctionDescriptor graphene_quaternion_init_from_euler$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_quaternion_init_from_euler$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_init_from_euler",
        constants$1245.graphene_quaternion_init_from_euler$FUNC
    );
    static final FunctionDescriptor graphene_quaternion_to_vec4$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_quaternion_to_vec4$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_to_vec4",
        constants$1245.graphene_quaternion_to_vec4$FUNC
    );
    static final FunctionDescriptor graphene_quaternion_to_matrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_quaternion_to_matrix$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_to_matrix",
        constants$1245.graphene_quaternion_to_matrix$FUNC
    );
    static final FunctionDescriptor graphene_quaternion_to_angles$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_quaternion_to_angles$MH = RuntimeHelper.downcallHandle(
        "graphene_quaternion_to_angles",
        constants$1245.graphene_quaternion_to_angles$FUNC
    );
}


