// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$200 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$200() {}
    static final FunctionDescriptor g_io_channel_set_buffered$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_io_channel_set_buffered$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_set_buffered",
        constants$200.g_io_channel_set_buffered$FUNC
    );
    static final FunctionDescriptor g_io_channel_get_buffered$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_get_buffered$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_get_buffered",
        constants$200.g_io_channel_get_buffered$FUNC
    );
    static final FunctionDescriptor g_io_channel_set_encoding$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_set_encoding$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_set_encoding",
        constants$200.g_io_channel_set_encoding$FUNC
    );
    static final FunctionDescriptor g_io_channel_get_encoding$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_get_encoding$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_get_encoding",
        constants$200.g_io_channel_get_encoding$FUNC
    );
    static final FunctionDescriptor g_io_channel_set_close_on_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_io_channel_set_close_on_unref$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_set_close_on_unref",
        constants$200.g_io_channel_set_close_on_unref$FUNC
    );
    static final FunctionDescriptor g_io_channel_get_close_on_unref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_get_close_on_unref$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_get_close_on_unref",
        constants$200.g_io_channel_get_close_on_unref$FUNC
    );
}


