// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1191 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1191() {}
    static final FunctionDescriptor __ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __ilogbf$MH = RuntimeHelper.downcallHandle(
        "__ilogbf",
        constants$1191.__ilogbf$FUNC
    );
    static final FunctionDescriptor scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle scalblnf$MH = RuntimeHelper.downcallHandle(
        "scalblnf",
        constants$1191.scalblnf$FUNC
    );
    static final FunctionDescriptor __scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __scalblnf$MH = RuntimeHelper.downcallHandle(
        "__scalblnf",
        constants$1191.__scalblnf$FUNC
    );
    static final FunctionDescriptor nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nearbyintf$MH = RuntimeHelper.downcallHandle(
        "nearbyintf",
        constants$1191.nearbyintf$FUNC
    );
    static final FunctionDescriptor __nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __nearbyintf$MH = RuntimeHelper.downcallHandle(
        "__nearbyintf",
        constants$1191.__nearbyintf$FUNC
    );
    static final FunctionDescriptor roundf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle roundf$MH = RuntimeHelper.downcallHandle(
        "roundf",
        constants$1191.roundf$FUNC
    );
}


