// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1306 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1306() {}
    static final FunctionDescriptor gtk_accelerator_valid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accelerator_valid$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_valid",
        constants$1306.gtk_accelerator_valid$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_parse$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_accelerator_parse$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_parse",
        constants$1306.gtk_accelerator_parse$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_parse_with_keycode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_accelerator_parse_with_keycode$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_parse_with_keycode",
        constants$1306.gtk_accelerator_parse_with_keycode$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accelerator_name$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_name",
        constants$1306.gtk_accelerator_name$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_name_with_keycode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accelerator_name_with_keycode$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_name_with_keycode",
        constants$1306.gtk_accelerator_name_with_keycode$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_get_label$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accelerator_get_label$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_get_label",
        constants$1306.gtk_accelerator_get_label$FUNC
    );
}


