// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1483 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1483() {}
    static final FunctionDescriptor gtk_tree_view_column_clear$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_clear$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_clear",
        constants$1483.gtk_tree_view_column_clear$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_column_add_attribute$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_add_attribute$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_add_attribute",
        constants$1483.gtk_tree_view_column_add_attribute$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_column_set_attributes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_set_attributes$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_tree_view_column_set_attributes",
        constants$1483.gtk_tree_view_column_set_attributes$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_column_set_cell_data_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_set_cell_data_func$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_set_cell_data_func",
        constants$1483.gtk_tree_view_column_set_cell_data_func$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_column_clear_attributes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_clear_attributes$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_clear_attributes",
        constants$1483.gtk_tree_view_column_clear_attributes$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_column_set_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_set_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_set_spacing",
        constants$1483.gtk_tree_view_column_set_spacing$FUNC
    );
}


