// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1357 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1357() {}
    static final FunctionDescriptor gtk_window_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_destroy$MH = RuntimeHelper.downcallHandle(
        "gtk_window_destroy",
        constants$1357.gtk_window_destroy$FUNC
    );
    static final FunctionDescriptor gtk_window_set_interactive_debugging$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_interactive_debugging$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_interactive_debugging",
        constants$1357.gtk_window_set_interactive_debugging$FUNC
    );
    static final FunctionDescriptor gtk_window_set_handle_menubar_accel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_handle_menubar_accel$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_handle_menubar_accel",
        constants$1357.gtk_window_set_handle_menubar_accel$FUNC
    );
    static final FunctionDescriptor gtk_window_get_handle_menubar_accel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_handle_menubar_accel$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_handle_menubar_accel",
        constants$1357.gtk_window_get_handle_menubar_accel$FUNC
    );
    static final FunctionDescriptor gtk_about_dialog_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_about_dialog_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_get_type",
        constants$1357.gtk_about_dialog_get_type$FUNC
    );
    static final FunctionDescriptor gtk_about_dialog_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_about_dialog_new$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_new",
        constants$1357.gtk_about_dialog_new$FUNC
    );
}


