// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$257 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$257() {}
    static final FunctionDescriptor g_queue_get_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_get_length$MH = RuntimeHelper.downcallHandle(
        "g_queue_get_length",
        constants$257.g_queue_get_length$FUNC
    );
    static final FunctionDescriptor g_queue_reverse$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_reverse$MH = RuntimeHelper.downcallHandle(
        "g_queue_reverse",
        constants$257.g_queue_reverse$FUNC
    );
    static final FunctionDescriptor g_queue_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_copy$MH = RuntimeHelper.downcallHandle(
        "g_queue_copy",
        constants$257.g_queue_copy$FUNC
    );
    static final FunctionDescriptor g_queue_foreach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_foreach$MH = RuntimeHelper.downcallHandle(
        "g_queue_foreach",
        constants$257.g_queue_foreach$FUNC
    );
    static final FunctionDescriptor g_queue_find$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_find$MH = RuntimeHelper.downcallHandle(
        "g_queue_find",
        constants$257.g_queue_find$FUNC
    );
    static final FunctionDescriptor g_queue_find_custom$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_find_custom$MH = RuntimeHelper.downcallHandle(
        "g_queue_find_custom",
        constants$257.g_queue_find_custom$FUNC
    );
}


