// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1518 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1518() {}
    static final FunctionDescriptor gtk_entry_get_alignment$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_alignment$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_alignment",
        constants$1518.gtk_entry_get_alignment$FUNC
    );
    static final FunctionDescriptor gtk_entry_set_completion$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_set_completion$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_completion",
        constants$1518.gtk_entry_set_completion$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_completion$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_completion$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_completion",
        constants$1518.gtk_entry_get_completion$FUNC
    );
    static final FunctionDescriptor gtk_entry_set_progress_fraction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_entry_set_progress_fraction$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_progress_fraction",
        constants$1518.gtk_entry_set_progress_fraction$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_progress_fraction$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_progress_fraction$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_progress_fraction",
        constants$1518.gtk_entry_get_progress_fraction$FUNC
    );
    static final FunctionDescriptor gtk_entry_set_progress_pulse_step$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_entry_set_progress_pulse_step$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_progress_pulse_step",
        constants$1518.gtk_entry_set_progress_pulse_step$FUNC
    );
}


