// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1673 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1673() {}
    static final FunctionDescriptor gtk_info_bar_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_info_bar_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_get_type",
        constants$1673.gtk_info_bar_get_type$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_info_bar_new$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_new",
        constants$1673.gtk_info_bar_new$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_new_with_buttons$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_new_with_buttons$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_info_bar_new_with_buttons",
        constants$1673.gtk_info_bar_new_with_buttons$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_add_action_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_add_action_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_add_action_widget",
        constants$1673.gtk_info_bar_add_action_widget$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_remove_action_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_remove_action_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_remove_action_widget",
        constants$1673.gtk_info_bar_remove_action_widget$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_add_button$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_add_button$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_add_button",
        constants$1673.gtk_info_bar_add_button$FUNC
    );
}


