// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1034 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1034() {}
    static final FunctionDescriptor gdk_rgba_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_free$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_free",
        constants$1034.gdk_rgba_free$FUNC
    );
    static final FunctionDescriptor gdk_rgba_is_clear$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_is_clear$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_is_clear",
        constants$1034.gdk_rgba_is_clear$FUNC
    );
    static final FunctionDescriptor gdk_rgba_is_opaque$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_is_opaque$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_is_opaque",
        constants$1034.gdk_rgba_is_opaque$FUNC
    );
    static final FunctionDescriptor gdk_rgba_hash$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_hash$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_hash",
        constants$1034.gdk_rgba_hash$FUNC
    );
    static final FunctionDescriptor gdk_rgba_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_equal$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_equal",
        constants$1034.gdk_rgba_equal$FUNC
    );
    static final FunctionDescriptor gdk_rgba_parse$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_rgba_parse$MH = RuntimeHelper.downcallHandle(
        "gdk_rgba_parse",
        constants$1034.gdk_rgba_parse$FUNC
    );
}


