// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1829 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1829() {}
    static final FunctionDescriptor gtk_snapshot_gl_shader_pop_texture$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_gl_shader_pop_texture$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_gl_shader_pop_texture",
        constants$1829.gtk_snapshot_gl_shader_pop_texture$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_pop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_pop$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_pop",
        constants$1829.gtk_snapshot_pop$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_save$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_save$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_save",
        constants$1829.gtk_snapshot_save$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_restore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_restore$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_restore",
        constants$1829.gtk_snapshot_restore$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_transform$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_transform$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_transform",
        constants$1829.gtk_snapshot_transform$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_transform_matrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_transform_matrix$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_transform_matrix",
        constants$1829.gtk_snapshot_transform_matrix$FUNC
    );
}


