// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$368 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$368() {}
    static final FunctionDescriptor g_static_rec_mutex_unlock_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_unlock_full$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_unlock_full",
        constants$368.g_static_rec_mutex_unlock_full$FUNC
    );
    static final FunctionDescriptor g_static_rec_mutex_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_free$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_free",
        constants$368.g_static_rec_mutex_free$FUNC
    );
    static final FunctionDescriptor g_static_rw_lock_init$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rw_lock_init$MH = RuntimeHelper.downcallHandle(
        "g_static_rw_lock_init",
        constants$368.g_static_rw_lock_init$FUNC
    );
    static final FunctionDescriptor g_static_rw_lock_reader_lock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rw_lock_reader_lock$MH = RuntimeHelper.downcallHandle(
        "g_static_rw_lock_reader_lock",
        constants$368.g_static_rw_lock_reader_lock$FUNC
    );
    static final FunctionDescriptor g_static_rw_lock_reader_trylock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rw_lock_reader_trylock$MH = RuntimeHelper.downcallHandle(
        "g_static_rw_lock_reader_trylock",
        constants$368.g_static_rw_lock_reader_trylock$FUNC
    );
    static final FunctionDescriptor g_static_rw_lock_reader_unlock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rw_lock_reader_unlock$MH = RuntimeHelper.downcallHandle(
        "g_static_rw_lock_reader_unlock",
        constants$368.g_static_rw_lock_reader_unlock$FUNC
    );
}


