// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$654 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$654() {}
    static final FunctionDescriptor g_inet_address_get_is_mc_global$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_global$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_global",
        constants$654.g_inet_address_get_is_mc_global$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_link_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_link_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_link_local",
        constants$654.g_inet_address_get_is_mc_link_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_node_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_node_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_node_local",
        constants$654.g_inet_address_get_is_mc_node_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_org_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_org_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_org_local",
        constants$654.g_inet_address_get_is_mc_org_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_site_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_site_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_site_local",
        constants$654.g_inet_address_get_is_mc_site_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_mask_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_inet_address_mask_get_type$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_mask_get_type",
        constants$654.g_inet_address_mask_get_type$FUNC
    );
}


