// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1060 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1060() {}
    static final FunctionDescriptor pango_cairo_font_map_get_default$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle pango_cairo_font_map_get_default$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_get_default",
        constants$1060.pango_cairo_font_map_get_default$FUNC
    );
    static final FunctionDescriptor pango_cairo_font_map_set_default$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_cairo_font_map_set_default$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_set_default",
        constants$1060.pango_cairo_font_map_set_default$FUNC
    );
    static final FunctionDescriptor pango_cairo_font_map_get_font_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_cairo_font_map_get_font_type$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_get_font_type",
        constants$1060.pango_cairo_font_map_get_font_type$FUNC
    );
    static final FunctionDescriptor pango_cairo_font_map_set_resolution$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle pango_cairo_font_map_set_resolution$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_set_resolution",
        constants$1060.pango_cairo_font_map_set_resolution$FUNC
    );
    static final FunctionDescriptor pango_cairo_font_map_get_resolution$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_cairo_font_map_get_resolution$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_get_resolution",
        constants$1060.pango_cairo_font_map_get_resolution$FUNC
    );
    static final FunctionDescriptor pango_cairo_font_map_create_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_cairo_font_map_create_context$MH = RuntimeHelper.downcallHandle(
        "pango_cairo_font_map_create_context",
        constants$1060.pango_cairo_font_map_create_context$FUNC
    );
}


