// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1507 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1507() {}
    static final FunctionDescriptor gtk_entry_completion_new_with_area$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_new_with_area$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_new_with_area",
        constants$1507.gtk_entry_completion_new_with_area$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_get_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_get_entry$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_get_entry",
        constants$1507.gtk_entry_completion_get_entry$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_set_model$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_set_model$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_set_model",
        constants$1507.gtk_entry_completion_set_model$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_get_model$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_get_model$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_get_model",
        constants$1507.gtk_entry_completion_get_model$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_set_match_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_set_match_func$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_set_match_func",
        constants$1507.gtk_entry_completion_set_match_func$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_set_minimum_key_length$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_set_minimum_key_length$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_set_minimum_key_length",
        constants$1507.gtk_entry_completion_set_minimum_key_length$FUNC
    );
}


