// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1601 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1601() {}
    static final FunctionDescriptor gtk_fixed_layout_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_fixed_layout_new$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_layout_new",
        constants$1601.gtk_fixed_layout_new$FUNC
    );
    static final FunctionDescriptor gtk_fixed_layout_child_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_fixed_layout_child_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_layout_child_get_type",
        constants$1601.gtk_fixed_layout_child_get_type$FUNC
    );
    static final FunctionDescriptor gtk_fixed_layout_child_set_transform$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_fixed_layout_child_set_transform$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_layout_child_set_transform",
        constants$1601.gtk_fixed_layout_child_set_transform$FUNC
    );
    static final FunctionDescriptor gtk_fixed_layout_child_get_transform$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_fixed_layout_child_get_transform$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_layout_child_get_transform",
        constants$1601.gtk_fixed_layout_child_get_transform$FUNC
    );
    static final FunctionDescriptor gtk_file_filter_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_file_filter_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_file_filter_get_type",
        constants$1601.gtk_file_filter_get_type$FUNC
    );
    static final FunctionDescriptor gtk_file_filter_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_file_filter_new$MH = RuntimeHelper.downcallHandle(
        "gtk_file_filter_new",
        constants$1601.gtk_file_filter_new$FUNC
    );
}


