// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$665 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$665() {}
    static final FunctionDescriptor g_bus_name_watcher_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_bus_name_watcher_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_bus_name_watcher_flags_get_type",
        constants$665.g_bus_name_watcher_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_proxy_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_proxy_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_flags_get_type",
        constants$665.g_dbus_proxy_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_error_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_error_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_error_get_type",
        constants$665.g_dbus_error_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_connection_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_connection_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_flags_get_type",
        constants$665.g_dbus_connection_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_capability_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_capability_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_capability_flags_get_type",
        constants$665.g_dbus_capability_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_call_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_call_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_call_flags_get_type",
        constants$665.g_dbus_call_flags_get_type$FUNC
    );
}


