// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1791 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1791() {}
    static final FunctionDescriptor gtk_recent_info_get_modified$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_get_modified$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_get_modified",
        constants$1791.gtk_recent_info_get_modified$FUNC
    );
    static final FunctionDescriptor gtk_recent_info_get_visited$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_get_visited$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_get_visited",
        constants$1791.gtk_recent_info_get_visited$FUNC
    );
    static final FunctionDescriptor gtk_recent_info_get_private_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_get_private_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_get_private_hint",
        constants$1791.gtk_recent_info_get_private_hint$FUNC
    );
    static final FunctionDescriptor gtk_recent_info_get_application_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_get_application_info$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_get_application_info",
        constants$1791.gtk_recent_info_get_application_info$FUNC
    );
    static final FunctionDescriptor gtk_recent_info_create_app_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_create_app_info$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_create_app_info",
        constants$1791.gtk_recent_info_create_app_info$FUNC
    );
    static final FunctionDescriptor gtk_recent_info_get_applications$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_recent_info_get_applications$MH = RuntimeHelper.downcallHandle(
        "gtk_recent_info_get_applications",
        constants$1791.gtk_recent_info_get_applications$FUNC
    );
}


