// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1186 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1186() {}
    static final FunctionDescriptor __j1f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __j1f$MH = RuntimeHelper.downcallHandle(
        "__j1f",
        constants$1186.__j1f$FUNC
    );
    static final FunctionDescriptor jnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle jnf$MH = RuntimeHelper.downcallHandle(
        "jnf",
        constants$1186.jnf$FUNC
    );
    static final FunctionDescriptor __jnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __jnf$MH = RuntimeHelper.downcallHandle(
        "__jnf",
        constants$1186.__jnf$FUNC
    );
    static final FunctionDescriptor y0f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle y0f$MH = RuntimeHelper.downcallHandle(
        "y0f",
        constants$1186.y0f$FUNC
    );
    static final FunctionDescriptor __y0f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __y0f$MH = RuntimeHelper.downcallHandle(
        "__y0f",
        constants$1186.__y0f$FUNC
    );
    static final FunctionDescriptor y1f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle y1f$MH = RuntimeHelper.downcallHandle(
        "y1f",
        constants$1186.y1f$FUNC
    );
}


