// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1755 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1755() {}
    static final FunctionDescriptor gtk_picture_new_for_resource$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_new_for_resource$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_new_for_resource",
        constants$1755.gtk_picture_new_for_resource$FUNC
    );
    static final FunctionDescriptor gtk_picture_set_paintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_set_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_set_paintable",
        constants$1755.gtk_picture_set_paintable$FUNC
    );
    static final FunctionDescriptor gtk_picture_get_paintable$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_get_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_get_paintable",
        constants$1755.gtk_picture_get_paintable$FUNC
    );
    static final FunctionDescriptor gtk_picture_set_file$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_set_file$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_set_file",
        constants$1755.gtk_picture_set_file$FUNC
    );
    static final FunctionDescriptor gtk_picture_get_file$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_get_file$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_get_file",
        constants$1755.gtk_picture_get_file$FUNC
    );
    static final FunctionDescriptor gtk_picture_set_filename$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_picture_set_filename$MH = RuntimeHelper.downcallHandle(
        "gtk_picture_set_filename",
        constants$1755.gtk_picture_set_filename$FUNC
    );
}


