// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1388 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1388() {}
    static final FunctionDescriptor gtk_at_context_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_at_context_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_at_context_get_type",
        constants$1388.gtk_at_context_get_type$FUNC
    );
    static final FunctionDescriptor gtk_at_context_get_accessible$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_at_context_get_accessible$MH = RuntimeHelper.downcallHandle(
        "gtk_at_context_get_accessible",
        constants$1388.gtk_at_context_get_accessible$FUNC
    );
    static final FunctionDescriptor gtk_at_context_get_accessible_role$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_at_context_get_accessible_role$MH = RuntimeHelper.downcallHandle(
        "gtk_at_context_get_accessible_role",
        constants$1388.gtk_at_context_get_accessible_role$FUNC
    );
    static final FunctionDescriptor gtk_at_context_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_at_context_create$MH = RuntimeHelper.downcallHandle(
        "gtk_at_context_create",
        constants$1388.gtk_at_context_create$FUNC
    );
    static final FunctionDescriptor gtk_layout_child_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_layout_child_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_child_get_type",
        constants$1388.gtk_layout_child_get_type$FUNC
    );
    static final FunctionDescriptor gtk_layout_child_get_layout_manager$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_layout_child_get_layout_manager$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_child_get_layout_manager",
        constants$1388.gtk_layout_child_get_layout_manager$FUNC
    );
}


