// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1250 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1250() {}
    static final FunctionDescriptor graphene_euler_get_alpha$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_get_alpha$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_get_alpha",
        constants$1250.graphene_euler_get_alpha$FUNC
    );
    static final FunctionDescriptor graphene_euler_get_beta$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_get_beta$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_get_beta",
        constants$1250.graphene_euler_get_beta$FUNC
    );
    static final FunctionDescriptor graphene_euler_get_gamma$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_get_gamma$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_get_gamma",
        constants$1250.graphene_euler_get_gamma$FUNC
    );
    static final FunctionDescriptor graphene_euler_to_vec3$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_to_vec3$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_to_vec3",
        constants$1250.graphene_euler_to_vec3$FUNC
    );
    static final FunctionDescriptor graphene_euler_to_matrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_to_matrix$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_to_matrix",
        constants$1250.graphene_euler_to_matrix$FUNC
    );
    static final FunctionDescriptor graphene_euler_to_quaternion$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_euler_to_quaternion$MH = RuntimeHelper.downcallHandle(
        "graphene_euler_to_quaternion",
        constants$1250.graphene_euler_to_quaternion$FUNC
    );
}


