// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1133() {}
    static final FunctionDescriptor gdk_gl_context_set_use_es$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_gl_context_set_use_es$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_set_use_es",
        constants$1133.gdk_gl_context_set_use_es$FUNC
    );
    static final FunctionDescriptor gdk_gl_context_get_use_es$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_gl_context_get_use_es$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_get_use_es",
        constants$1133.gdk_gl_context_get_use_es$FUNC
    );
    static final FunctionDescriptor gdk_gl_context_realize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_gl_context_realize$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_realize",
        constants$1133.gdk_gl_context_realize$FUNC
    );
    static final FunctionDescriptor gdk_gl_context_make_current$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_gl_context_make_current$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_make_current",
        constants$1133.gdk_gl_context_make_current$FUNC
    );
    static final FunctionDescriptor gdk_gl_context_get_current$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gdk_gl_context_get_current$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_get_current",
        constants$1133.gdk_gl_context_get_current$FUNC
    );
    static final FunctionDescriptor gdk_gl_context_clear_current$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle gdk_gl_context_clear_current$MH = RuntimeHelper.downcallHandle(
        "gdk_gl_context_clear_current",
        constants$1133.gdk_gl_context_clear_current$FUNC
    );
}


