// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1636 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1636() {}
    static final FunctionDescriptor gtk_gesture_drag_get_start_point$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_drag_get_start_point$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_drag_get_start_point",
        constants$1636.gtk_gesture_drag_get_start_point$FUNC
    );
    static final FunctionDescriptor gtk_gesture_drag_get_offset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_drag_get_offset$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_drag_get_offset",
        constants$1636.gtk_gesture_drag_get_offset$FUNC
    );
    static final FunctionDescriptor gtk_gesture_long_press_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_gesture_long_press_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_get_type",
        constants$1636.gtk_gesture_long_press_get_type$FUNC
    );
    static final FunctionDescriptor gtk_gesture_long_press_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_gesture_long_press_new$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_new",
        constants$1636.gtk_gesture_long_press_new$FUNC
    );
    static final FunctionDescriptor gtk_gesture_long_press_set_delay_factor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_gesture_long_press_set_delay_factor$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_set_delay_factor",
        constants$1636.gtk_gesture_long_press_set_delay_factor$FUNC
    );
    static final FunctionDescriptor gtk_gesture_long_press_get_delay_factor$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_long_press_get_delay_factor$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_get_delay_factor",
        constants$1636.gtk_gesture_long_press_get_delay_factor$FUNC
    );
}


