// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1802 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1802() {}
    static final FunctionDescriptor gtk_scale_button_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_button_get_value$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_get_value",
        constants$1802.gtk_scale_button_get_value$FUNC
    );
    static final FunctionDescriptor gtk_scale_button_set_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_scale_button_set_value$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_set_value",
        constants$1802.gtk_scale_button_set_value$FUNC
    );
    static final FunctionDescriptor gtk_scale_button_get_adjustment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_button_get_adjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_get_adjustment",
        constants$1802.gtk_scale_button_get_adjustment$FUNC
    );
    static final FunctionDescriptor gtk_scale_button_set_adjustment$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_button_set_adjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_set_adjustment",
        constants$1802.gtk_scale_button_set_adjustment$FUNC
    );
    static final FunctionDescriptor gtk_scale_button_get_plus_button$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_button_get_plus_button$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_get_plus_button",
        constants$1802.gtk_scale_button_get_plus_button$FUNC
    );
    static final FunctionDescriptor gtk_scale_button_get_minus_button$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_button_get_minus_button$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_button_get_minus_button",
        constants$1802.gtk_scale_button_get_minus_button$FUNC
    );
}


