// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$564 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$564() {}
    static final FunctionDescriptor g_dbus_message_get_message_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_message_get_message_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_get_message_type",
        constants$564.g_dbus_message_get_message_type$FUNC
    );
    static final FunctionDescriptor g_dbus_message_set_message_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_message_set_message_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_set_message_type",
        constants$564.g_dbus_message_set_message_type$FUNC
    );
    static final FunctionDescriptor g_dbus_message_get_flags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_message_get_flags$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_get_flags",
        constants$564.g_dbus_message_get_flags$FUNC
    );
    static final FunctionDescriptor g_dbus_message_set_flags$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_message_set_flags$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_set_flags",
        constants$564.g_dbus_message_set_flags$FUNC
    );
    static final FunctionDescriptor g_dbus_message_get_serial$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_message_get_serial$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_get_serial",
        constants$564.g_dbus_message_get_serial$FUNC
    );
    static final FunctionDescriptor g_dbus_message_set_serial$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_message_set_serial$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_set_serial",
        constants$564.g_dbus_message_set_serial$FUNC
    );
}


