// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1307 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1307() {}
    static final FunctionDescriptor gtk_accelerator_get_label_with_keycode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accelerator_get_label_with_keycode$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_get_label_with_keycode",
        constants$1307.gtk_accelerator_get_label_with_keycode$FUNC
    );
    static final FunctionDescriptor gtk_accelerator_get_default_mod_mask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_accelerator_get_default_mod_mask$MH = RuntimeHelper.downcallHandle(
        "gtk_accelerator_get_default_mod_mask",
        constants$1307.gtk_accelerator_get_default_mod_mask$FUNC
    );
    static final FunctionDescriptor gtk_border_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_border_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_border_get_type",
        constants$1307.gtk_border_get_type$FUNC
    );
    static final FunctionDescriptor gtk_border_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_border_new$MH = RuntimeHelper.downcallHandle(
        "gtk_border_new",
        constants$1307.gtk_border_new$FUNC
    );
    static final FunctionDescriptor gtk_border_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_border_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_border_copy",
        constants$1307.gtk_border_copy$FUNC
    );
    static final FunctionDescriptor gtk_border_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_border_free$MH = RuntimeHelper.downcallHandle(
        "gtk_border_free",
        constants$1307.gtk_border_free$FUNC
    );
}


