// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$230 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$230() {}
    static final FunctionDescriptor g_variant_dup_bytestring_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_bytestring_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_bytestring_array",
        constants$230.g_variant_dup_bytestring_array$FUNC
    );
    static final FunctionDescriptor g_variant_new_maybe$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_new_maybe$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_maybe",
        constants$230.g_variant_new_maybe$FUNC
    );
    static final FunctionDescriptor g_variant_new_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_variant_new_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_array",
        constants$230.g_variant_new_array$FUNC
    );
    static final FunctionDescriptor g_variant_new_tuple$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_variant_new_tuple$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_tuple",
        constants$230.g_variant_new_tuple$FUNC
    );
    static final FunctionDescriptor g_variant_new_dict_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_new_dict_entry$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_dict_entry",
        constants$230.g_variant_new_dict_entry$FUNC
    );
    static final FunctionDescriptor g_variant_get_maybe$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_maybe$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_maybe",
        constants$230.g_variant_get_maybe$FUNC
    );
}


