// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$163 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$163() {}
    static final FunctionDescriptor GSourceDisposeFunc_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GSourceDisposeFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$163.GSourceDisposeFunc_DOWN$FUNC
    );
    static final FunctionDescriptor GSourceDummyMarshal$FUNC = FunctionDescriptor.ofVoid();
    static final FunctionDescriptor GSourceDummyMarshal_UP$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle GSourceDummyMarshal_UP$MH = RuntimeHelper.upcallHandle(GSourceDummyMarshal.class, "apply", constants$163.GSourceDummyMarshal_UP$FUNC);
    static final FunctionDescriptor GSourceDummyMarshal_DOWN$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle GSourceDummyMarshal_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$163.GSourceDummyMarshal_DOWN$FUNC
    );
    static final FunctionDescriptor g_main_context_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_main_context_new$MH = RuntimeHelper.downcallHandle(
        "g_main_context_new",
        constants$163.g_main_context_new$FUNC
    );
    static final FunctionDescriptor g_main_context_new_with_flags$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_main_context_new_with_flags$MH = RuntimeHelper.downcallHandle(
        "g_main_context_new_with_flags",
        constants$163.g_main_context_new_with_flags$FUNC
    );
    static final FunctionDescriptor g_main_context_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_main_context_ref$MH = RuntimeHelper.downcallHandle(
        "g_main_context_ref",
        constants$163.g_main_context_ref$FUNC
    );
}


