// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1573 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1573() {}
    static final FunctionDescriptor gtk_constraint_layout_observe_guides$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_constraint_layout_observe_guides$MH = RuntimeHelper.downcallHandle(
        "gtk_constraint_layout_observe_guides",
        constants$1573.gtk_constraint_layout_observe_guides$FUNC
    );
    static final FunctionDescriptor gtk_css_provider_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_css_provider_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_css_provider_get_type",
        constants$1573.gtk_css_provider_get_type$FUNC
    );
    static final FunctionDescriptor gtk_css_provider_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_css_provider_new$MH = RuntimeHelper.downcallHandle(
        "gtk_css_provider_new",
        constants$1573.gtk_css_provider_new$FUNC
    );
    static final FunctionDescriptor gtk_css_provider_to_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_css_provider_to_string$MH = RuntimeHelper.downcallHandle(
        "gtk_css_provider_to_string",
        constants$1573.gtk_css_provider_to_string$FUNC
    );
    static final FunctionDescriptor gtk_css_provider_load_from_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_css_provider_load_from_data$MH = RuntimeHelper.downcallHandle(
        "gtk_css_provider_load_from_data",
        constants$1573.gtk_css_provider_load_from_data$FUNC
    );
    static final FunctionDescriptor gtk_css_provider_load_from_file$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_css_provider_load_from_file$MH = RuntimeHelper.downcallHandle(
        "gtk_css_provider_load_from_file",
        constants$1573.gtk_css_provider_load_from_file$FUNC
    );
}


