// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1316 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1316() {}
    static final FunctionDescriptor gtk_widget_get_preferred_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_preferred_size$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_preferred_size",
        constants$1316.gtk_widget_get_preferred_size$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_layout_manager$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_set_layout_manager$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_layout_manager",
        constants$1316.gtk_widget_set_layout_manager$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_layout_manager$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_layout_manager$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_layout_manager",
        constants$1316.gtk_widget_get_layout_manager$FUNC
    );
    static final FunctionDescriptor gtk_widget_class_set_layout_manager_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_class_set_layout_manager_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_class_set_layout_manager_type",
        constants$1316.gtk_widget_class_set_layout_manager_type$FUNC
    );
    static final FunctionDescriptor gtk_widget_class_get_layout_manager_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_class_get_layout_manager_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_class_get_layout_manager_type",
        constants$1316.gtk_widget_class_get_layout_manager_type$FUNC
    );
    static final FunctionDescriptor gtk_widget_class_add_binding$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_class_add_binding$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_widget_class_add_binding",
        constants$1316.gtk_widget_class_add_binding$FUNC
    );
}


