// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$667 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$667() {}
    static final FunctionDescriptor g_dbus_signal_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_signal_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_signal_flags_get_type",
        constants$667.g_dbus_signal_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_send_message_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_send_message_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_send_message_flags_get_type",
        constants$667.g_dbus_send_message_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_credentials_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_credentials_type_get_type$MH = RuntimeHelper.downcallHandle(
        "g_credentials_type_get_type",
        constants$667.g_credentials_type_get_type$FUNC
    );
    static final FunctionDescriptor g_dbus_message_byte_order_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_message_byte_order_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_byte_order_get_type",
        constants$667.g_dbus_message_byte_order_get_type$FUNC
    );
    static final FunctionDescriptor g_application_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_application_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_application_flags_get_type",
        constants$667.g_application_flags_get_type$FUNC
    );
    static final FunctionDescriptor g_tls_error_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_tls_error_get_type$MH = RuntimeHelper.downcallHandle(
        "g_tls_error_get_type",
        constants$667.g_tls_error_get_type$FUNC
    );
}


