// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1276 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1276() {}
    static final FunctionDescriptor gsk_serialization_error_quark$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gsk_serialization_error_quark$MH = RuntimeHelper.downcallHandle(
        "gsk_serialization_error_quark",
        constants$1276.gsk_serialization_error_quark$FUNC
    );
    static final FunctionDescriptor gsk_render_node_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_render_node_ref$MH = RuntimeHelper.downcallHandle(
        "gsk_render_node_ref",
        constants$1276.gsk_render_node_ref$FUNC
    );
    static final FunctionDescriptor gsk_render_node_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_render_node_unref$MH = RuntimeHelper.downcallHandle(
        "gsk_render_node_unref",
        constants$1276.gsk_render_node_unref$FUNC
    );
    static final FunctionDescriptor gsk_render_node_get_node_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_render_node_get_node_type$MH = RuntimeHelper.downcallHandle(
        "gsk_render_node_get_node_type",
        constants$1276.gsk_render_node_get_node_type$FUNC
    );
    static final FunctionDescriptor gsk_render_node_get_bounds$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_render_node_get_bounds$MH = RuntimeHelper.downcallHandle(
        "gsk_render_node_get_bounds",
        constants$1276.gsk_render_node_get_bounds$FUNC
    );
    static final FunctionDescriptor gsk_render_node_draw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_render_node_draw$MH = RuntimeHelper.downcallHandle(
        "gsk_render_node_draw",
        constants$1276.gsk_render_node_draw$FUNC
    );
}


