// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1531 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1531() {}
    static final FunctionDescriptor gtk_tree_view_collapse_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_collapse_all$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_collapse_all",
        constants$1531.gtk_tree_view_collapse_all$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_expand_to_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_expand_to_path$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_expand_to_path",
        constants$1531.gtk_tree_view_expand_to_path$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_expand_row$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_view_expand_row$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_expand_row",
        constants$1531.gtk_tree_view_expand_row$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_collapse_row$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_collapse_row$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_collapse_row",
        constants$1531.gtk_tree_view_collapse_row$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_map_expanded_rows$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_map_expanded_rows$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_map_expanded_rows",
        constants$1531.gtk_tree_view_map_expanded_rows$FUNC
    );
    static final FunctionDescriptor gtk_tree_view_row_expanded$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_row_expanded$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_row_expanded",
        constants$1531.gtk_tree_view_row_expanded$FUNC
    );
}


