// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1499 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1499() {}
    static final FunctionDescriptor gtk_entry_buffer_set_max_length$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_set_max_length$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_set_max_length",
        constants$1499.gtk_entry_buffer_set_max_length$FUNC
    );
    static final FunctionDescriptor gtk_entry_buffer_get_max_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_get_max_length$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_get_max_length",
        constants$1499.gtk_entry_buffer_get_max_length$FUNC
    );
    static final FunctionDescriptor gtk_entry_buffer_insert_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_insert_text$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_insert_text",
        constants$1499.gtk_entry_buffer_insert_text$FUNC
    );
    static final FunctionDescriptor gtk_entry_buffer_delete_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_delete_text$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_delete_text",
        constants$1499.gtk_entry_buffer_delete_text$FUNC
    );
    static final FunctionDescriptor gtk_entry_buffer_emit_inserted_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_emit_inserted_text$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_emit_inserted_text",
        constants$1499.gtk_entry_buffer_emit_inserted_text$FUNC
    );
    static final FunctionDescriptor gtk_entry_buffer_emit_deleted_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_buffer_emit_deleted_text$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_buffer_emit_deleted_text",
        constants$1499.gtk_entry_buffer_emit_deleted_text$FUNC
    );
}


