// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$627 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$627() {}
    static final FunctionDescriptor g_file_replace_contents_bytes_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_replace_contents_bytes_async$MH = RuntimeHelper.downcallHandle(
        "g_file_replace_contents_bytes_async",
        constants$627.g_file_replace_contents_bytes_async$FUNC
    );
    static final FunctionDescriptor g_file_replace_contents_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_replace_contents_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_replace_contents_finish",
        constants$627.g_file_replace_contents_finish$FUNC
    );
    static final FunctionDescriptor g_file_supports_thread_contexts$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_supports_thread_contexts$MH = RuntimeHelper.downcallHandle(
        "g_file_supports_thread_contexts",
        constants$627.g_file_supports_thread_contexts$FUNC
    );
    static final FunctionDescriptor g_file_load_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_load_bytes$MH = RuntimeHelper.downcallHandle(
        "g_file_load_bytes",
        constants$627.g_file_load_bytes$FUNC
    );
    static final FunctionDescriptor g_file_load_bytes_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_load_bytes_async$MH = RuntimeHelper.downcallHandle(
        "g_file_load_bytes_async",
        constants$627.g_file_load_bytes_async$FUNC
    );
    static final FunctionDescriptor g_file_load_bytes_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_load_bytes_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_load_bytes_finish",
        constants$627.g_file_load_bytes_finish$FUNC
    );
}


