// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$650 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$650() {}
    static final FunctionDescriptor g_filename_completer_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_filename_completer_new$MH = RuntimeHelper.downcallHandle(
        "g_filename_completer_new",
        constants$650.g_filename_completer_new$FUNC
    );
    static final FunctionDescriptor g_filename_completer_get_completion_suffix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_filename_completer_get_completion_suffix$MH = RuntimeHelper.downcallHandle(
        "g_filename_completer_get_completion_suffix",
        constants$650.g_filename_completer_get_completion_suffix$FUNC
    );
    static final FunctionDescriptor g_filename_completer_get_completions$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_filename_completer_get_completions$MH = RuntimeHelper.downcallHandle(
        "g_filename_completer_get_completions",
        constants$650.g_filename_completer_get_completions$FUNC
    );
    static final FunctionDescriptor g_filename_completer_set_dirs_only$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_filename_completer_set_dirs_only$MH = RuntimeHelper.downcallHandle(
        "g_filename_completer_set_dirs_only",
        constants$650.g_filename_completer_set_dirs_only$FUNC
    );
    static final FunctionDescriptor g_file_output_stream_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_file_output_stream_get_type$MH = RuntimeHelper.downcallHandle(
        "g_file_output_stream_get_type",
        constants$650.g_file_output_stream_get_type$FUNC
    );
    static final FunctionDescriptor g_file_output_stream_query_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_output_stream_query_info$MH = RuntimeHelper.downcallHandle(
        "g_file_output_stream_query_info",
        constants$650.g_file_output_stream_query_info$FUNC
    );
}


