// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1074 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1074() {}
    static final FunctionDescriptor gdk_content_formats_get_gtypes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_get_gtypes$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_get_gtypes",
        constants$1074.gdk_content_formats_get_gtypes$FUNC
    );
    static final FunctionDescriptor gdk_content_formats_get_mime_types$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_get_mime_types$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_get_mime_types",
        constants$1074.gdk_content_formats_get_mime_types$FUNC
    );
    static final FunctionDescriptor gdk_content_formats_union$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_union$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_union",
        constants$1074.gdk_content_formats_union$FUNC
    );
    static final FunctionDescriptor gdk_content_formats_match$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_match$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_match",
        constants$1074.gdk_content_formats_match$FUNC
    );
    static final FunctionDescriptor gdk_content_formats_match_gtype$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_match_gtype$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_match_gtype",
        constants$1074.gdk_content_formats_match_gtype$FUNC
    );
    static final FunctionDescriptor gdk_content_formats_match_mime_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_match_mime_type$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_match_mime_type",
        constants$1074.gdk_content_formats_match_mime_type$FUNC
    );
}


