// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final FunctionDescriptor g_get_language_names_with_category$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_get_language_names_with_category$MH = RuntimeHelper.downcallHandle(
        "g_get_language_names_with_category",
        constants$100.g_get_language_names_with_category$FUNC
    );
    static final FunctionDescriptor g_get_locale_variants$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_get_locale_variants$MH = RuntimeHelper.downcallHandle(
        "g_get_locale_variants",
        constants$100.g_get_locale_variants$FUNC
    );
    static final FunctionDescriptor g_checksum_type_get_length$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_checksum_type_get_length$MH = RuntimeHelper.downcallHandle(
        "g_checksum_type_get_length",
        constants$100.g_checksum_type_get_length$FUNC
    );
    static final FunctionDescriptor g_checksum_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_checksum_new$MH = RuntimeHelper.downcallHandle(
        "g_checksum_new",
        constants$100.g_checksum_new$FUNC
    );
    static final FunctionDescriptor g_checksum_reset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_checksum_reset$MH = RuntimeHelper.downcallHandle(
        "g_checksum_reset",
        constants$100.g_checksum_reset$FUNC
    );
    static final FunctionDescriptor g_checksum_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_checksum_copy$MH = RuntimeHelper.downcallHandle(
        "g_checksum_copy",
        constants$100.g_checksum_copy$FUNC
    );
}


