// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1327 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1327() {}
    static final FunctionDescriptor gtk_widget_set_overflow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_overflow$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_overflow",
        constants$1327.gtk_widget_set_overflow$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_overflow$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_overflow$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_overflow",
        constants$1327.gtk_widget_get_overflow$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_ancestor$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_get_ancestor$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_ancestor",
        constants$1327.gtk_widget_get_ancestor$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_scale_factor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_scale_factor$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_scale_factor",
        constants$1327.gtk_widget_get_scale_factor$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_display$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_display",
        constants$1327.gtk_widget_get_display$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_settings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_settings",
        constants$1327.gtk_widget_get_settings$FUNC
    );
}


