// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$381 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$381() {}
    static final FunctionDescriptor g_type_add_instance_private$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_type_add_instance_private$MH = RuntimeHelper.downcallHandle(
        "g_type_add_instance_private",
        constants$381.g_type_add_instance_private$FUNC
    );
    static final FunctionDescriptor g_type_instance_get_private$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_type_instance_get_private$MH = RuntimeHelper.downcallHandle(
        "g_type_instance_get_private",
        constants$381.g_type_instance_get_private$FUNC
    );
    static final FunctionDescriptor g_type_class_adjust_private_offset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_class_adjust_private_offset$MH = RuntimeHelper.downcallHandle(
        "g_type_class_adjust_private_offset",
        constants$381.g_type_class_adjust_private_offset$FUNC
    );
    static final FunctionDescriptor g_type_add_class_private$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_type_add_class_private$MH = RuntimeHelper.downcallHandle(
        "g_type_add_class_private",
        constants$381.g_type_add_class_private$FUNC
    );
    static final FunctionDescriptor g_type_class_get_private$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_type_class_get_private$MH = RuntimeHelper.downcallHandle(
        "g_type_class_get_private",
        constants$381.g_type_class_get_private$FUNC
    );
    static final FunctionDescriptor g_type_class_get_instance_private_offset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_class_get_instance_private_offset$MH = RuntimeHelper.downcallHandle(
        "g_type_class_get_instance_private_offset",
        constants$381.g_type_class_get_instance_private_offset$FUNC
    );
}


