// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1681 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1681() {}
    static final FunctionDescriptor gtk_label_get_wrap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_wrap$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_wrap",
        constants$1681.gtk_label_get_wrap$FUNC
    );
    static final FunctionDescriptor gtk_label_set_wrap_mode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_label_set_wrap_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_wrap_mode",
        constants$1681.gtk_label_set_wrap_mode$FUNC
    );
    static final FunctionDescriptor gtk_label_get_wrap_mode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_wrap_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_wrap_mode",
        constants$1681.gtk_label_get_wrap_mode$FUNC
    );
    static final FunctionDescriptor gtk_label_set_natural_wrap_mode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_label_set_natural_wrap_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_natural_wrap_mode",
        constants$1681.gtk_label_set_natural_wrap_mode$FUNC
    );
    static final FunctionDescriptor gtk_label_get_natural_wrap_mode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_natural_wrap_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_natural_wrap_mode",
        constants$1681.gtk_label_get_natural_wrap_mode$FUNC
    );
    static final FunctionDescriptor gtk_label_set_selectable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_label_set_selectable$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_selectable",
        constants$1681.gtk_label_set_selectable$FUNC
    );
}


