// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$534 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$534() {}
    static final FunctionDescriptor g_data_input_stream_read_int32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_int32$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_int32",
        constants$534.g_data_input_stream_read_int32$FUNC
    );
    static final FunctionDescriptor g_data_input_stream_read_uint32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_uint32$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_uint32",
        constants$534.g_data_input_stream_read_uint32$FUNC
    );
    static final FunctionDescriptor g_data_input_stream_read_int64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_int64$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_int64",
        constants$534.g_data_input_stream_read_int64$FUNC
    );
    static final FunctionDescriptor g_data_input_stream_read_uint64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_uint64$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_uint64",
        constants$534.g_data_input_stream_read_uint64$FUNC
    );
    static final FunctionDescriptor g_data_input_stream_read_line$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_line$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_line",
        constants$534.g_data_input_stream_read_line$FUNC
    );
    static final FunctionDescriptor g_data_input_stream_read_line_utf8$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_data_input_stream_read_line_utf8$MH = RuntimeHelper.downcallHandle(
        "g_data_input_stream_read_line_utf8",
        constants$534.g_data_input_stream_read_line_utf8$FUNC
    );
}


