// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1520 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1520() {}
    static final FunctionDescriptor gtk_entry_set_icon_from_gicon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_set_icon_from_gicon$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_icon_from_gicon",
        constants$1520.gtk_entry_set_icon_from_gicon$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_icon_storage_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_get_icon_storage_type$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_icon_storage_type",
        constants$1520.gtk_entry_get_icon_storage_type$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_icon_paintable$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_get_icon_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_icon_paintable",
        constants$1520.gtk_entry_get_icon_paintable$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_icon_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_get_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_icon_name",
        constants$1520.gtk_entry_get_icon_name$FUNC
    );
    static final FunctionDescriptor gtk_entry_get_icon_gicon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_get_icon_gicon$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_icon_gicon",
        constants$1520.gtk_entry_get_icon_gicon$FUNC
    );
    static final FunctionDescriptor gtk_entry_set_icon_activatable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_set_icon_activatable$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_icon_activatable",
        constants$1520.gtk_entry_set_icon_activatable$FUNC
    );
}


