// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1260 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1260() {}
    static final FunctionDescriptor graphene_box_get_center$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_get_center$MH = RuntimeHelper.downcallHandle(
        "graphene_box_get_center",
        constants$1260.graphene_box_get_center$FUNC
    );
    static final FunctionDescriptor graphene_box_get_min$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_get_min$MH = RuntimeHelper.downcallHandle(
        "graphene_box_get_min",
        constants$1260.graphene_box_get_min$FUNC
    );
    static final FunctionDescriptor graphene_box_get_max$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_get_max$MH = RuntimeHelper.downcallHandle(
        "graphene_box_get_max",
        constants$1260.graphene_box_get_max$FUNC
    );
    static final FunctionDescriptor graphene_box_get_vertices$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_get_vertices$MH = RuntimeHelper.downcallHandle(
        "graphene_box_get_vertices",
        constants$1260.graphene_box_get_vertices$FUNC
    );
    static final FunctionDescriptor graphene_box_get_bounding_sphere$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_get_bounding_sphere$MH = RuntimeHelper.downcallHandle(
        "graphene_box_get_bounding_sphere",
        constants$1260.graphene_box_get_bounding_sphere$FUNC
    );
    static final FunctionDescriptor graphene_box_contains_point$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_box_contains_point$MH = RuntimeHelper.downcallHandle(
        "graphene_box_contains_point",
        constants$1260.graphene_box_contains_point$FUNC
    );
}


