// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1826 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1826() {}
    static final FunctionDescriptor gtk_slice_list_model_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_slice_list_model_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_slice_list_model_get_size",
        constants$1826.gtk_slice_list_model_get_size$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_snapshot_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_get_type",
        constants$1826.gtk_snapshot_get_type$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_snapshot_new$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_new",
        constants$1826.gtk_snapshot_new$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_free_to_node$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_free_to_node$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_free_to_node",
        constants$1826.gtk_snapshot_free_to_node$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_free_to_paintable$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_free_to_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_free_to_paintable",
        constants$1826.gtk_snapshot_free_to_paintable$FUNC
    );
    static final FunctionDescriptor gtk_snapshot_to_node$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_snapshot_to_node$MH = RuntimeHelper.downcallHandle(
        "gtk_snapshot_to_node",
        constants$1826.gtk_snapshot_to_node$FUNC
    );
}


