// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$181 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$181() {}
    static final FunctionDescriptor g_unichar_isprint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isprint$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isprint",
        constants$181.g_unichar_isprint$FUNC
    );
    static final FunctionDescriptor g_unichar_ispunct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_ispunct$MH = RuntimeHelper.downcallHandle(
        "g_unichar_ispunct",
        constants$181.g_unichar_ispunct$FUNC
    );
    static final FunctionDescriptor g_unichar_isspace$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isspace$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isspace",
        constants$181.g_unichar_isspace$FUNC
    );
    static final FunctionDescriptor g_unichar_isupper$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isupper$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isupper",
        constants$181.g_unichar_isupper$FUNC
    );
    static final FunctionDescriptor g_unichar_isxdigit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_isxdigit$MH = RuntimeHelper.downcallHandle(
        "g_unichar_isxdigit",
        constants$181.g_unichar_isxdigit$FUNC
    );
    static final FunctionDescriptor g_unichar_istitle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_unichar_istitle$MH = RuntimeHelper.downcallHandle(
        "g_unichar_istitle",
        constants$181.g_unichar_istitle$FUNC
    );
}


