// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$843 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$843() {}
    static final FunctionDescriptor cairo_user_font_face_set_init_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_set_init_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_set_init_func",
        constants$843.cairo_user_font_face_set_init_func$FUNC
    );
    static final FunctionDescriptor cairo_user_font_face_set_render_glyph_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_set_render_glyph_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_set_render_glyph_func",
        constants$843.cairo_user_font_face_set_render_glyph_func$FUNC
    );
    static final FunctionDescriptor cairo_user_font_face_set_text_to_glyphs_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_set_text_to_glyphs_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_set_text_to_glyphs_func",
        constants$843.cairo_user_font_face_set_text_to_glyphs_func$FUNC
    );
    static final FunctionDescriptor cairo_user_font_face_set_unicode_to_glyph_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_set_unicode_to_glyph_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_set_unicode_to_glyph_func",
        constants$843.cairo_user_font_face_set_unicode_to_glyph_func$FUNC
    );
    static final FunctionDescriptor cairo_user_font_face_get_init_func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_get_init_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_get_init_func",
        constants$843.cairo_user_font_face_get_init_func$FUNC
    );
    static final FunctionDescriptor cairo_user_font_face_get_render_glyph_func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_user_font_face_get_render_glyph_func$MH = RuntimeHelper.downcallHandle(
        "cairo_user_font_face_get_render_glyph_func",
        constants$843.cairo_user_font_face_get_render_glyph_func$FUNC
    );
}


