// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$229 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$229() {}
    static final FunctionDescriptor g_variant_dup_strv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_strv$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_strv",
        constants$229.g_variant_dup_strv$FUNC
    );
    static final FunctionDescriptor g_variant_get_objv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_objv$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_objv",
        constants$229.g_variant_get_objv$FUNC
    );
    static final FunctionDescriptor g_variant_dup_objv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_objv$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_objv",
        constants$229.g_variant_dup_objv$FUNC
    );
    static final FunctionDescriptor g_variant_get_bytestring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_bytestring$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_bytestring",
        constants$229.g_variant_get_bytestring$FUNC
    );
    static final FunctionDescriptor g_variant_dup_bytestring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_bytestring$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_bytestring",
        constants$229.g_variant_dup_bytestring$FUNC
    );
    static final FunctionDescriptor g_variant_get_bytestring_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_bytestring_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_bytestring_array",
        constants$229.g_variant_get_bytestring_array$FUNC
    );
}


