// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1107() {}
    static final FunctionDescriptor gdk_popup_layout_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_popup_layout_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_get_type",
        constants$1107.gdk_popup_layout_get_type$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_new$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_new",
        constants$1107.gdk_popup_layout_new$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_ref$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_ref",
        constants$1107.gdk_popup_layout_ref$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_unref$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_unref",
        constants$1107.gdk_popup_layout_unref$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_copy$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_copy",
        constants$1107.gdk_popup_layout_copy$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_equal$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_equal",
        constants$1107.gdk_popup_layout_equal$FUNC
    );
}


