// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$452 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$452() {}
    static final FunctionDescriptor g_value_array_get_nth$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_value_array_get_nth$MH = RuntimeHelper.downcallHandle(
        "g_value_array_get_nth",
        constants$452.g_value_array_get_nth$FUNC
    );
    static final FunctionDescriptor g_value_array_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_value_array_new$MH = RuntimeHelper.downcallHandle(
        "g_value_array_new",
        constants$452.g_value_array_new$FUNC
    );
    static final FunctionDescriptor g_value_array_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_free$MH = RuntimeHelper.downcallHandle(
        "g_value_array_free",
        constants$452.g_value_array_free$FUNC
    );
    static final FunctionDescriptor g_value_array_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_copy$MH = RuntimeHelper.downcallHandle(
        "g_value_array_copy",
        constants$452.g_value_array_copy$FUNC
    );
    static final FunctionDescriptor g_value_array_prepend$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_prepend$MH = RuntimeHelper.downcallHandle(
        "g_value_array_prepend",
        constants$452.g_value_array_prepend$FUNC
    );
    static final FunctionDescriptor g_value_array_append$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_append$MH = RuntimeHelper.downcallHandle(
        "g_value_array_append",
        constants$452.g_value_array_append$FUNC
    );
}


