// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$928 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$928() {}
    static final FunctionDescriptor hb_set_invert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_invert$MH = RuntimeHelper.downcallHandle(
        "hb_set_invert",
        constants$928.hb_set_invert$FUNC
    );
    static final FunctionDescriptor hb_unicode_eastasian_width_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor hb_unicode_eastasian_width_func_t_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_eastasian_width_func_t_UP$MH = RuntimeHelper.upcallHandle(hb_unicode_eastasian_width_func_t.class, "apply", constants$928.hb_unicode_eastasian_width_func_t_UP$FUNC);
    static final FunctionDescriptor hb_unicode_eastasian_width_func_t_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_eastasian_width_func_t_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$928.hb_unicode_eastasian_width_func_t_DOWN$FUNC
    );
    static final FunctionDescriptor hb_unicode_funcs_set_eastasian_width_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_funcs_set_eastasian_width_func$MH = RuntimeHelper.downcallHandle(
        "hb_unicode_funcs_set_eastasian_width_func",
        constants$928.hb_unicode_funcs_set_eastasian_width_func$FUNC
    );
    static final FunctionDescriptor hb_unicode_eastasian_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_unicode_eastasian_width$MH = RuntimeHelper.downcallHandle(
        "hb_unicode_eastasian_width",
        constants$928.hb_unicode_eastasian_width$FUNC
    );
    static final FunctionDescriptor hb_unicode_decompose_compatibility_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor hb_unicode_decompose_compatibility_func_t_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_decompose_compatibility_func_t_UP$MH = RuntimeHelper.upcallHandle(hb_unicode_decompose_compatibility_func_t.class, "apply", constants$928.hb_unicode_decompose_compatibility_func_t_UP$FUNC);
}


