// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$929 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$929() {}
    static final FunctionDescriptor hb_unicode_decompose_compatibility_func_t_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_decompose_compatibility_func_t_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$929.hb_unicode_decompose_compatibility_func_t_DOWN$FUNC
    );
    static final FunctionDescriptor hb_unicode_funcs_set_decompose_compatibility_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_funcs_set_decompose_compatibility_func$MH = RuntimeHelper.downcallHandle(
        "hb_unicode_funcs_set_decompose_compatibility_func",
        constants$929.hb_unicode_funcs_set_decompose_compatibility_func$FUNC
    );
    static final FunctionDescriptor hb_unicode_decompose_compatibility$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_unicode_decompose_compatibility$MH = RuntimeHelper.downcallHandle(
        "hb_unicode_decompose_compatibility",
        constants$929.hb_unicode_decompose_compatibility$FUNC
    );
    static final FunctionDescriptor hb_font_get_glyph_v_kerning_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor hb_font_get_glyph_v_kerning_func_t_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_get_glyph_v_kerning_func_t_UP$MH = RuntimeHelper.upcallHandle(hb_font_get_glyph_v_kerning_func_t.class, "apply", constants$929.hb_font_get_glyph_v_kerning_func_t_UP$FUNC);
    static final FunctionDescriptor hb_font_get_glyph_v_kerning_func_t_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_get_glyph_v_kerning_func_t_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$929.hb_font_get_glyph_v_kerning_func_t_DOWN$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_set_glyph_v_kerning_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_funcs_set_glyph_v_kerning_func$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_set_glyph_v_kerning_func",
        constants$929.hb_font_funcs_set_glyph_v_kerning_func$FUNC
    );
}


