// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1888 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1888() {}
    static final FunctionDescriptor gtk_text_buffer_insert_markup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_insert_markup$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_insert_markup",
        constants$1888.gtk_text_buffer_insert_markup$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_delete$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_delete$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_delete",
        constants$1888.gtk_text_buffer_delete$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_delete_interactive$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_delete_interactive$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_delete_interactive",
        constants$1888.gtk_text_buffer_delete_interactive$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_backspace$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_backspace$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_backspace",
        constants$1888.gtk_text_buffer_backspace$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_get_text$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_get_text$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_get_text",
        constants$1888.gtk_text_buffer_get_text$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_get_slice$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_get_slice$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_get_slice",
        constants$1888.gtk_text_buffer_get_slice$FUNC
    );
}


