// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1325 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1325() {}
    static final FunctionDescriptor gtk_widget_compute_bounds$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_compute_bounds$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_compute_bounds",
        constants$1325.gtk_widget_compute_bounds$FUNC
    );
    static final FunctionDescriptor gtk_widget_compute_point$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_compute_point$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_compute_point",
        constants$1325.gtk_widget_compute_point$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_width$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_width",
        constants$1325.gtk_widget_get_width$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_height$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_height$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_height",
        constants$1325.gtk_widget_get_height$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_size",
        constants$1325.gtk_widget_get_size$FUNC
    );
    static final FunctionDescriptor gtk_widget_child_focus$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_child_focus$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_child_focus",
        constants$1325.gtk_widget_child_focus$FUNC
    );
}


