// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1046 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1046() {}
    static final FunctionDescriptor gdk_pixbuf_composite_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_composite_color$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_composite_color",
        constants$1046.gdk_pixbuf_composite_color$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_scale_simple$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_scale_simple$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_scale_simple",
        constants$1046.gdk_pixbuf_scale_simple$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_composite_color_simple$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_composite_color_simple$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_composite_color_simple",
        constants$1046.gdk_pixbuf_composite_color_simple$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_rotate_simple$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_rotate_simple$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_rotate_simple",
        constants$1046.gdk_pixbuf_rotate_simple$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_flip$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_flip$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_flip",
        constants$1046.gdk_pixbuf_flip$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_animation_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_pixbuf_animation_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_animation_get_type",
        constants$1046.gdk_pixbuf_animation_get_type$FUNC
    );
}


