// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1800 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1800() {}
    static final FunctionDescriptor gtk_scale_set_has_origin$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_scale_set_has_origin$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_set_has_origin",
        constants$1800.gtk_scale_set_has_origin$FUNC
    );
    static final FunctionDescriptor gtk_scale_get_has_origin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_get_has_origin$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_get_has_origin",
        constants$1800.gtk_scale_get_has_origin$FUNC
    );
    static final FunctionDescriptor gtk_scale_set_value_pos$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_scale_set_value_pos$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_set_value_pos",
        constants$1800.gtk_scale_set_value_pos$FUNC
    );
    static final FunctionDescriptor gtk_scale_get_value_pos$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_get_value_pos$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_get_value_pos",
        constants$1800.gtk_scale_get_value_pos$FUNC
    );
    static final FunctionDescriptor gtk_scale_get_layout$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_get_layout$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_get_layout",
        constants$1800.gtk_scale_get_layout$FUNC
    );
    static final FunctionDescriptor gtk_scale_get_layout_offsets$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_scale_get_layout_offsets$MH = RuntimeHelper.downcallHandle(
        "gtk_scale_get_layout_offsets",
        constants$1800.gtk_scale_get_layout_offsets$FUNC
    );
}


