// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1389 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1389() {}
    static final FunctionDescriptor gtk_layout_child_get_child_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_layout_child_get_child_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_child_get_child_widget",
        constants$1389.gtk_layout_child_get_child_widget$FUNC
    );
    static final FunctionDescriptor gtk_layout_manager_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_layout_manager_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_manager_get_type",
        constants$1389.gtk_layout_manager_get_type$FUNC
    );
    static final FunctionDescriptor gtk_layout_manager_measure$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_layout_manager_measure$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_manager_measure",
        constants$1389.gtk_layout_manager_measure$FUNC
    );
    static final FunctionDescriptor gtk_layout_manager_allocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_layout_manager_allocate$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_manager_allocate",
        constants$1389.gtk_layout_manager_allocate$FUNC
    );
    static final FunctionDescriptor gtk_layout_manager_get_request_mode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_layout_manager_get_request_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_manager_get_request_mode",
        constants$1389.gtk_layout_manager_get_request_mode$FUNC
    );
    static final FunctionDescriptor gtk_layout_manager_get_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_layout_manager_get_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_layout_manager_get_widget",
        constants$1389.gtk_layout_manager_get_widget$FUNC
    );
}


