// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1010 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1010() {}
    static final FunctionDescriptor pango_layout_iter_get_cluster_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_cluster_extents$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_cluster_extents",
        constants$1010.pango_layout_iter_get_cluster_extents$FUNC
    );
    static final FunctionDescriptor pango_layout_iter_get_run_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_run_extents$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_run_extents",
        constants$1010.pango_layout_iter_get_run_extents$FUNC
    );
    static final FunctionDescriptor pango_layout_iter_get_line_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_line_extents$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_line_extents",
        constants$1010.pango_layout_iter_get_line_extents$FUNC
    );
    static final FunctionDescriptor pango_layout_iter_get_line_yrange$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_line_yrange$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_line_yrange",
        constants$1010.pango_layout_iter_get_line_yrange$FUNC
    );
    static final FunctionDescriptor pango_layout_iter_get_layout_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_layout_extents$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_layout_extents",
        constants$1010.pango_layout_iter_get_layout_extents$FUNC
    );
    static final FunctionDescriptor pango_layout_iter_get_baseline$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_iter_get_baseline$MH = RuntimeHelper.downcallHandle(
        "pango_layout_iter_get_baseline",
        constants$1010.pango_layout_iter_get_baseline$FUNC
    );
}


