// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1902 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1902() {}
    static final FunctionDescriptor gtk_text_view_starts_display_line$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_view_starts_display_line$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_starts_display_line",
        constants$1902.gtk_text_view_starts_display_line$FUNC
    );
    static final FunctionDescriptor gtk_text_view_move_visually$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_view_move_visually$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_move_visually",
        constants$1902.gtk_text_view_move_visually$FUNC
    );
    static final FunctionDescriptor gtk_text_view_im_context_filter_keypress$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_view_im_context_filter_keypress$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_im_context_filter_keypress",
        constants$1902.gtk_text_view_im_context_filter_keypress$FUNC
    );
    static final FunctionDescriptor gtk_text_view_reset_im_context$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_view_reset_im_context$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_reset_im_context",
        constants$1902.gtk_text_view_reset_im_context$FUNC
    );
    static final FunctionDescriptor gtk_text_view_get_gutter$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_view_get_gutter$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_get_gutter",
        constants$1902.gtk_text_view_get_gutter$FUNC
    );
    static final FunctionDescriptor gtk_text_view_set_gutter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_view_set_gutter$MH = RuntimeHelper.downcallHandle(
        "gtk_text_view_set_gutter",
        constants$1902.gtk_text_view_set_gutter$FUNC
    );
}


