// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1078 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1078() {}
    static final FunctionDescriptor gdk_content_provider_write_mime_type_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_provider_write_mime_type_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_content_provider_write_mime_type_finish",
        constants$1078.gdk_content_provider_write_mime_type_finish$FUNC
    );
    static final FunctionDescriptor gdk_content_provider_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_provider_get_value$MH = RuntimeHelper.downcallHandle(
        "gdk_content_provider_get_value",
        constants$1078.gdk_content_provider_get_value$FUNC
    );
    static final FunctionDescriptor gdk_content_provider_new_for_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_provider_new_for_value$MH = RuntimeHelper.downcallHandle(
        "gdk_content_provider_new_for_value",
        constants$1078.gdk_content_provider_new_for_value$FUNC
    );
    static final FunctionDescriptor gdk_content_provider_new_typed$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gdk_content_provider_new_typed$MH = RuntimeHelper.downcallHandleVariadic(
        "gdk_content_provider_new_typed",
        constants$1078.gdk_content_provider_new_typed$FUNC
    );
    static final FunctionDescriptor gdk_content_provider_new_union$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gdk_content_provider_new_union$MH = RuntimeHelper.downcallHandle(
        "gdk_content_provider_new_union",
        constants$1078.gdk_content_provider_new_union$FUNC
    );
    static final FunctionDescriptor gdk_content_provider_new_for_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_provider_new_for_bytes$MH = RuntimeHelper.downcallHandle(
        "gdk_content_provider_new_for_bytes",
        constants$1078.gdk_content_provider_new_for_bytes$FUNC
    );
}


