// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1069 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1069() {}
    static final FunctionDescriptor gdk_clipboard_set_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_clipboard_set_text$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_set_text",
        constants$1069.gdk_clipboard_set_text$FUNC
    );
    static final FunctionDescriptor gdk_clipboard_set_texture$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_clipboard_set_texture$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_set_texture",
        constants$1069.gdk_clipboard_set_texture$FUNC
    );
    static final FunctionDescriptor GdkContentDeserializeFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor GdkContentDeserializeFunc_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GdkContentDeserializeFunc_UP$MH = RuntimeHelper.upcallHandle(GdkContentDeserializeFunc.class, "apply", constants$1069.GdkContentDeserializeFunc_UP$FUNC);
    static final FunctionDescriptor GdkContentDeserializeFunc_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GdkContentDeserializeFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$1069.GdkContentDeserializeFunc_DOWN$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_content_deserializer_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_type",
        constants$1069.gdk_content_deserializer_get_type$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_mime_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_mime_type$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_mime_type",
        constants$1069.gdk_content_deserializer_get_mime_type$FUNC
    );
}


