// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1006 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1006() {}
    static final FunctionDescriptor pango_layout_line_is_paragraph_start$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_is_paragraph_start$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_is_paragraph_start",
        constants$1006.pango_layout_line_is_paragraph_start$FUNC
    );
    static final FunctionDescriptor pango_layout_line_get_resolved_direction$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_get_resolved_direction$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_get_resolved_direction",
        constants$1006.pango_layout_line_get_resolved_direction$FUNC
    );
    static final FunctionDescriptor pango_layout_line_x_to_index$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_x_to_index$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_x_to_index",
        constants$1006.pango_layout_line_x_to_index$FUNC
    );
    static final FunctionDescriptor pango_layout_line_index_to_x$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_index_to_x$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_index_to_x",
        constants$1006.pango_layout_line_index_to_x$FUNC
    );
    static final FunctionDescriptor pango_layout_line_get_x_ranges$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_get_x_ranges$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_get_x_ranges",
        constants$1006.pango_layout_line_get_x_ranges$FUNC
    );
    static final FunctionDescriptor pango_layout_line_get_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_line_get_extents$MH = RuntimeHelper.downcallHandle(
        "pango_layout_line_get_extents",
        constants$1006.pango_layout_line_get_extents$FUNC
    );
}


