// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$481 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$481() {}
    static final FunctionDescriptor g_application_add_main_option$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_add_main_option$MH = RuntimeHelper.downcallHandle(
        "g_application_add_main_option",
        constants$481.g_application_add_main_option$FUNC
    );
    static final FunctionDescriptor g_application_add_option_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_add_option_group$MH = RuntimeHelper.downcallHandle(
        "g_application_add_option_group",
        constants$481.g_application_add_option_group$FUNC
    );
    static final FunctionDescriptor g_application_set_option_context_parameter_string$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_set_option_context_parameter_string$MH = RuntimeHelper.downcallHandle(
        "g_application_set_option_context_parameter_string",
        constants$481.g_application_set_option_context_parameter_string$FUNC
    );
    static final FunctionDescriptor g_application_set_option_context_summary$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_set_option_context_summary$MH = RuntimeHelper.downcallHandle(
        "g_application_set_option_context_summary",
        constants$481.g_application_set_option_context_summary$FUNC
    );
    static final FunctionDescriptor g_application_set_option_context_description$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_set_option_context_description$MH = RuntimeHelper.downcallHandle(
        "g_application_set_option_context_description",
        constants$481.g_application_set_option_context_description$FUNC
    );
    static final FunctionDescriptor g_application_get_is_registered$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_application_get_is_registered$MH = RuntimeHelper.downcallHandle(
        "g_application_get_is_registered",
        constants$481.g_application_get_is_registered$FUNC
    );
}


