// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1912 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1912() {}
    static final FunctionDescriptor gtk_tree_row_data_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_row_data_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_data_get_type",
        constants$1912.gtk_tree_row_data_get_type$FUNC
    );
    static final FunctionDescriptor gtk_tree_drag_source_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_drag_source_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_drag_source_get_type",
        constants$1912.gtk_tree_drag_source_get_type$FUNC
    );
    static final FunctionDescriptor gtk_tree_drag_source_row_draggable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_drag_source_row_draggable$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_drag_source_row_draggable",
        constants$1912.gtk_tree_drag_source_row_draggable$FUNC
    );
    static final FunctionDescriptor gtk_tree_drag_source_drag_data_delete$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_drag_source_drag_data_delete$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_drag_source_drag_data_delete",
        constants$1912.gtk_tree_drag_source_drag_data_delete$FUNC
    );
    static final FunctionDescriptor gtk_tree_drag_source_drag_data_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_drag_source_drag_data_get$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_drag_source_drag_data_get",
        constants$1912.gtk_tree_drag_source_drag_data_get$FUNC
    );
    static final FunctionDescriptor gtk_tree_drag_dest_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_drag_dest_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_drag_dest_get_type",
        constants$1912.gtk_tree_drag_dest_get_type$FUNC
    );
}


