// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$592 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$592() {}
    static final FunctionDescriptor g_drive_get_symbolic_icon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_get_symbolic_icon$MH = RuntimeHelper.downcallHandle(
        "g_drive_get_symbolic_icon",
        constants$592.g_drive_get_symbolic_icon$FUNC
    );
    static final FunctionDescriptor g_drive_has_volumes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_has_volumes$MH = RuntimeHelper.downcallHandle(
        "g_drive_has_volumes",
        constants$592.g_drive_has_volumes$FUNC
    );
    static final FunctionDescriptor g_drive_get_volumes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_get_volumes$MH = RuntimeHelper.downcallHandle(
        "g_drive_get_volumes",
        constants$592.g_drive_get_volumes$FUNC
    );
    static final FunctionDescriptor g_drive_is_removable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_is_removable$MH = RuntimeHelper.downcallHandle(
        "g_drive_is_removable",
        constants$592.g_drive_is_removable$FUNC
    );
    static final FunctionDescriptor g_drive_is_media_removable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_is_media_removable$MH = RuntimeHelper.downcallHandle(
        "g_drive_is_media_removable",
        constants$592.g_drive_is_media_removable$FUNC
    );
    static final FunctionDescriptor g_drive_has_media$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_drive_has_media$MH = RuntimeHelper.downcallHandle(
        "g_drive_has_media",
        constants$592.g_drive_has_media$FUNC
    );
}


