// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$876 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$876() {}
    static final FunctionDescriptor cairo_region_union_rectangle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_union_rectangle$MH = RuntimeHelper.downcallHandle(
        "cairo_region_union_rectangle",
        constants$876.cairo_region_union_rectangle$FUNC
    );
    static final FunctionDescriptor cairo_region_xor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_xor$MH = RuntimeHelper.downcallHandle(
        "cairo_region_xor",
        constants$876.cairo_region_xor$FUNC
    );
    static final FunctionDescriptor cairo_region_xor_rectangle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_xor_rectangle$MH = RuntimeHelper.downcallHandle(
        "cairo_region_xor_rectangle",
        constants$876.cairo_region_xor_rectangle$FUNC
    );
    static final FunctionDescriptor cairo_debug_reset_static_data$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle cairo_debug_reset_static_data$MH = RuntimeHelper.downcallHandle(
        "cairo_debug_reset_static_data",
        constants$876.cairo_debug_reset_static_data$FUNC
    );
    static final FunctionDescriptor hb_tag_from_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_tag_from_string$MH = RuntimeHelper.downcallHandle(
        "hb_tag_from_string",
        constants$876.hb_tag_from_string$FUNC
    );
    static final FunctionDescriptor hb_tag_to_string$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_tag_to_string$MH = RuntimeHelper.downcallHandle(
        "hb_tag_to_string",
        constants$876.hb_tag_to_string$FUNC
    );
}


