// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1430 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1430() {}
    static final FunctionDescriptor gtk_tree_path_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_path_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_copy",
        constants$1430.gtk_tree_path_copy$FUNC
    );
    static final FunctionDescriptor gtk_tree_path_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_path_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_get_type",
        constants$1430.gtk_tree_path_get_type$FUNC
    );
    static final FunctionDescriptor gtk_tree_path_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_path_compare$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_compare",
        constants$1430.gtk_tree_path_compare$FUNC
    );
    static final FunctionDescriptor gtk_tree_path_next$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_path_next$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_next",
        constants$1430.gtk_tree_path_next$FUNC
    );
    static final FunctionDescriptor gtk_tree_path_prev$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_path_prev$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_prev",
        constants$1430.gtk_tree_path_prev$FUNC
    );
    static final FunctionDescriptor gtk_tree_path_up$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_path_up$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_path_up",
        constants$1430.gtk_tree_path_up$FUNC
    );
}


