// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1043 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1043() {}
    static final FunctionDescriptor gdk_pixbuf_new_from_stream_at_scale$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_new_from_stream_at_scale$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_new_from_stream_at_scale",
        constants$1043.gdk_pixbuf_new_from_stream_at_scale$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_new_from_stream_at_scale_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_new_from_stream_at_scale_async$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_new_from_stream_at_scale_async",
        constants$1043.gdk_pixbuf_new_from_stream_at_scale_async$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_save_to_stream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_save_to_stream$MH = RuntimeHelper.downcallHandleVariadic(
        "gdk_pixbuf_save_to_stream",
        constants$1043.gdk_pixbuf_save_to_stream$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_save_to_stream_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_save_to_stream_async$MH = RuntimeHelper.downcallHandleVariadic(
        "gdk_pixbuf_save_to_stream_async",
        constants$1043.gdk_pixbuf_save_to_stream_async$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_save_to_stream_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_save_to_stream_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_save_to_stream_finish",
        constants$1043.gdk_pixbuf_save_to_stream_finish$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_save_to_streamv_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_save_to_streamv_async$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_save_to_streamv_async",
        constants$1043.gdk_pixbuf_save_to_streamv_async$FUNC
    );
}


