// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1562 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1562() {}
    static final FunctionDescriptor gtk_accessible_tristate_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_tristate_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_tristate_get_type",
        constants$1562.gtk_accessible_tristate_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_invalid_state_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_invalid_state_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_invalid_state_get_type",
        constants$1562.gtk_accessible_invalid_state_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_autocomplete_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_autocomplete_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_autocomplete_get_type",
        constants$1562.gtk_accessible_autocomplete_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_sort_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_sort_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_sort_get_type",
        constants$1562.gtk_accessible_sort_get_type$FUNC
    );
    static final FunctionDescriptor gtk_event_controller_scroll_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_event_controller_scroll_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_event_controller_scroll_flags_get_type",
        constants$1562.gtk_event_controller_scroll_flags_get_type$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_action_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_file_chooser_action_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_action_get_type",
        constants$1562.gtk_file_chooser_action_get_type$FUNC
    );
}


