// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1148() {}
    static final FunctionDescriptor __signbit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __signbit$MH = RuntimeHelper.downcallHandle(
        "__signbit",
        constants$1148.__signbit$FUNC
    );
    static final FunctionDescriptor __isinf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isinf$MH = RuntimeHelper.downcallHandle(
        "__isinf",
        constants$1148.__isinf$FUNC
    );
    static final FunctionDescriptor __finite$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __finite$MH = RuntimeHelper.downcallHandle(
        "__finite",
        constants$1148.__finite$FUNC
    );
    static final FunctionDescriptor __isnan$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isnan$MH = RuntimeHelper.downcallHandle(
        "__isnan",
        constants$1148.__isnan$FUNC
    );
    static final FunctionDescriptor __iseqsig$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __iseqsig$MH = RuntimeHelper.downcallHandle(
        "__iseqsig",
        constants$1148.__iseqsig$FUNC
    );
    static final FunctionDescriptor __issignaling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __issignaling$MH = RuntimeHelper.downcallHandle(
        "__issignaling",
        constants$1148.__issignaling$FUNC
    );
}


