// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$582 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$582() {}
    static final FunctionDescriptor g_dbus_object_skeleton_flush$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_object_skeleton_flush$MH = RuntimeHelper.downcallHandle(
        "g_dbus_object_skeleton_flush",
        constants$582.g_dbus_object_skeleton_flush$FUNC
    );
    static final FunctionDescriptor g_dbus_object_skeleton_add_interface$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_object_skeleton_add_interface$MH = RuntimeHelper.downcallHandle(
        "g_dbus_object_skeleton_add_interface",
        constants$582.g_dbus_object_skeleton_add_interface$FUNC
    );
    static final FunctionDescriptor g_dbus_object_skeleton_remove_interface$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_object_skeleton_remove_interface$MH = RuntimeHelper.downcallHandle(
        "g_dbus_object_skeleton_remove_interface",
        constants$582.g_dbus_object_skeleton_remove_interface$FUNC
    );
    static final FunctionDescriptor g_dbus_object_skeleton_remove_interface_by_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_object_skeleton_remove_interface_by_name$MH = RuntimeHelper.downcallHandle(
        "g_dbus_object_skeleton_remove_interface_by_name",
        constants$582.g_dbus_object_skeleton_remove_interface_by_name$FUNC
    );
    static final FunctionDescriptor g_dbus_object_skeleton_set_object_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_object_skeleton_set_object_path$MH = RuntimeHelper.downcallHandle(
        "g_dbus_object_skeleton_set_object_path",
        constants$582.g_dbus_object_skeleton_set_object_path$FUNC
    );
    static final FunctionDescriptor g_dbus_proxy_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_proxy_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_type",
        constants$582.g_dbus_proxy_get_type$FUNC
    );
}


