// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1365 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1365() {}
    static final FunctionDescriptor gtk_accessible_reset_state$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accessible_reset_state$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_reset_state",
        constants$1365.gtk_accessible_reset_state$FUNC
    );
    static final FunctionDescriptor gtk_accessible_reset_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accessible_reset_property$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_reset_property",
        constants$1365.gtk_accessible_reset_property$FUNC
    );
    static final FunctionDescriptor gtk_accessible_reset_relation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_accessible_reset_relation$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_reset_relation",
        constants$1365.gtk_accessible_reset_relation$FUNC
    );
    static final FunctionDescriptor gtk_accessible_state_init_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_accessible_state_init_value$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_state_init_value",
        constants$1365.gtk_accessible_state_init_value$FUNC
    );
    static final FunctionDescriptor gtk_accessible_property_init_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_accessible_property_init_value$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_property_init_value",
        constants$1365.gtk_accessible_property_init_value$FUNC
    );
    static final FunctionDescriptor gtk_accessible_relation_init_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_accessible_relation_init_value$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_relation_init_value",
        constants$1365.gtk_accessible_relation_init_value$FUNC
    );
}


