// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$464 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$464() {}
    static final FunctionDescriptor GCancellableSourceFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor GCancellableSourceFunc_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GCancellableSourceFunc_UP$MH = RuntimeHelper.upcallHandle(GCancellableSourceFunc.class, "apply", constants$464.GCancellableSourceFunc_UP$FUNC);
    static final FunctionDescriptor GCancellableSourceFunc_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GCancellableSourceFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$464.GCancellableSourceFunc_DOWN$FUNC
    );
    static final FunctionDescriptor GPollableSourceFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor GPollableSourceFunc_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GPollableSourceFunc_UP$MH = RuntimeHelper.upcallHandle(GPollableSourceFunc.class, "apply", constants$464.GPollableSourceFunc_UP$FUNC);
    static final FunctionDescriptor GPollableSourceFunc_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GPollableSourceFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$464.GPollableSourceFunc_DOWN$FUNC
    );
    static final FunctionDescriptor GDBusProxyTypeFunc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor GDBusProxyTypeFunc_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GDBusProxyTypeFunc_UP$MH = RuntimeHelper.upcallHandle(GDBusProxyTypeFunc.class, "apply", constants$464.GDBusProxyTypeFunc_UP$FUNC);
    static final FunctionDescriptor GDBusProxyTypeFunc_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GDBusProxyTypeFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$464.GDBusProxyTypeFunc_DOWN$FUNC
    );
}


