// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$839 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$839() {}
    static final FunctionDescriptor cairo_scaled_font_get_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_user_data$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_user_data",
        constants$839.cairo_scaled_font_get_user_data$FUNC
    );
    static final FunctionDescriptor cairo_scaled_font_set_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_set_user_data$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_set_user_data",
        constants$839.cairo_scaled_font_set_user_data$FUNC
    );
    static final FunctionDescriptor cairo_scaled_font_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_extents$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_extents",
        constants$839.cairo_scaled_font_extents$FUNC
    );
    static final FunctionDescriptor cairo_scaled_font_text_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_text_extents$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_text_extents",
        constants$839.cairo_scaled_font_text_extents$FUNC
    );
    static final FunctionDescriptor cairo_scaled_font_glyph_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_glyph_extents$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_glyph_extents",
        constants$839.cairo_scaled_font_glyph_extents$FUNC
    );
    static final FunctionDescriptor cairo_scaled_font_text_to_glyphs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_text_to_glyphs$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_text_to_glyphs",
        constants$839.cairo_scaled_font_text_to_glyphs$FUNC
    );
}


