// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$623 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$623() {}
    static final FunctionDescriptor g_file_build_attribute_list_for_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_build_attribute_list_for_copy$MH = RuntimeHelper.downcallHandle(
        "g_file_build_attribute_list_for_copy",
        constants$623.g_file_build_attribute_list_for_copy$FUNC
    );
    static final FunctionDescriptor g_file_copy_attributes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_copy_attributes$MH = RuntimeHelper.downcallHandle(
        "g_file_copy_attributes",
        constants$623.g_file_copy_attributes$FUNC
    );
    static final FunctionDescriptor g_file_monitor_directory$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_monitor_directory$MH = RuntimeHelper.downcallHandle(
        "g_file_monitor_directory",
        constants$623.g_file_monitor_directory$FUNC
    );
    static final FunctionDescriptor g_file_monitor_file$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_monitor_file$MH = RuntimeHelper.downcallHandle(
        "g_file_monitor_file",
        constants$623.g_file_monitor_file$FUNC
    );
    static final FunctionDescriptor g_file_monitor$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_monitor$MH = RuntimeHelper.downcallHandle(
        "g_file_monitor",
        constants$623.g_file_monitor$FUNC
    );
    static final FunctionDescriptor g_file_measure_disk_usage$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_measure_disk_usage$MH = RuntimeHelper.downcallHandle(
        "g_file_measure_disk_usage",
        constants$623.g_file_measure_disk_usage$FUNC
    );
}


