// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$261 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$261() {}
    static final FunctionDescriptor g_queue_push_head_link$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_push_head_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_push_head_link",
        constants$261.g_queue_push_head_link$FUNC
    );
    static final FunctionDescriptor g_queue_push_tail_link$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_push_tail_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_push_tail_link",
        constants$261.g_queue_push_tail_link$FUNC
    );
    static final FunctionDescriptor g_queue_push_nth_link$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_push_nth_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_push_nth_link",
        constants$261.g_queue_push_nth_link$FUNC
    );
    static final FunctionDescriptor g_queue_pop_head_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_pop_head_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_pop_head_link",
        constants$261.g_queue_pop_head_link$FUNC
    );
    static final FunctionDescriptor g_queue_pop_tail_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_queue_pop_tail_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_pop_tail_link",
        constants$261.g_queue_pop_tail_link$FUNC
    );
    static final FunctionDescriptor g_queue_pop_nth_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_queue_pop_nth_link$MH = RuntimeHelper.downcallHandle(
        "g_queue_pop_nth_link",
        constants$261.g_queue_pop_nth_link$FUNC
    );
}


