// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1599 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1599() {}
    static final FunctionDescriptor gtk_expander_get_resize_toplevel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_resize_toplevel$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_resize_toplevel",
        constants$1599.gtk_expander_get_resize_toplevel$FUNC
    );
    static final FunctionDescriptor gtk_expander_set_child$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_set_child$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_child",
        constants$1599.gtk_expander_set_child$FUNC
    );
    static final FunctionDescriptor gtk_expander_get_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_child$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_child",
        constants$1599.gtk_expander_get_child$FUNC
    );
    static final FunctionDescriptor gtk_fixed_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_fixed_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_get_type",
        constants$1599.gtk_fixed_get_type$FUNC
    );
    static final FunctionDescriptor gtk_fixed_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_fixed_new$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_new",
        constants$1599.gtk_fixed_new$FUNC
    );
    static final FunctionDescriptor gtk_fixed_put$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_fixed_put$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_put",
        constants$1599.gtk_fixed_put$FUNC
    );
}


