// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$688 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$688() {}
    static final FunctionDescriptor g_menu_link_iter_next$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_link_iter_next$MH = RuntimeHelper.downcallHandle(
        "g_menu_link_iter_next",
        constants$688.g_menu_link_iter_next$FUNC
    );
    static final FunctionDescriptor g_menu_link_iter_get_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_link_iter_get_name$MH = RuntimeHelper.downcallHandle(
        "g_menu_link_iter_get_name",
        constants$688.g_menu_link_iter_get_name$FUNC
    );
    static final FunctionDescriptor g_menu_link_iter_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_link_iter_get_value$MH = RuntimeHelper.downcallHandle(
        "g_menu_link_iter_get_value",
        constants$688.g_menu_link_iter_get_value$FUNC
    );
    static final FunctionDescriptor g_menu_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_menu_get_type$MH = RuntimeHelper.downcallHandle(
        "g_menu_get_type",
        constants$688.g_menu_get_type$FUNC
    );
    static final FunctionDescriptor g_menu_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_menu_new$MH = RuntimeHelper.downcallHandle(
        "g_menu_new",
        constants$688.g_menu_new$FUNC
    );
    static final FunctionDescriptor g_menu_freeze$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_freeze$MH = RuntimeHelper.downcallHandle(
        "g_menu_freeze",
        constants$688.g_menu_freeze$FUNC
    );
}


