// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1393 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1393() {}
    static final FunctionDescriptor gtk_bitset_remove_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_bitset_remove_all$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_remove_all",
        constants$1393.gtk_bitset_remove_all$FUNC
    );
    static final FunctionDescriptor gtk_bitset_add$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_bitset_add$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_add",
        constants$1393.gtk_bitset_add$FUNC
    );
    static final FunctionDescriptor gtk_bitset_remove$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_bitset_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_remove",
        constants$1393.gtk_bitset_remove$FUNC
    );
    static final FunctionDescriptor gtk_bitset_add_range$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_bitset_add_range$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_add_range",
        constants$1393.gtk_bitset_add_range$FUNC
    );
    static final FunctionDescriptor gtk_bitset_remove_range$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_bitset_remove_range$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_remove_range",
        constants$1393.gtk_bitset_remove_range$FUNC
    );
    static final FunctionDescriptor gtk_bitset_add_range_closed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_bitset_add_range_closed$MH = RuntimeHelper.downcallHandle(
        "gtk_bitset_add_range_closed",
        constants$1393.gtk_bitset_add_range_closed$FUNC
    );
}


