// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1508 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1508() {}
    static final FunctionDescriptor gtk_entry_completion_get_minimum_key_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_get_minimum_key_length$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_get_minimum_key_length",
        constants$1508.gtk_entry_completion_get_minimum_key_length$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_compute_prefix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_compute_prefix$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_compute_prefix",
        constants$1508.gtk_entry_completion_compute_prefix$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_complete$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_complete$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_complete",
        constants$1508.gtk_entry_completion_complete$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_insert_prefix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_insert_prefix$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_insert_prefix",
        constants$1508.gtk_entry_completion_insert_prefix$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_set_inline_completion$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_set_inline_completion$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_set_inline_completion",
        constants$1508.gtk_entry_completion_set_inline_completion$FUNC
    );
    static final FunctionDescriptor gtk_entry_completion_get_inline_completion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_completion_get_inline_completion$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_completion_get_inline_completion",
        constants$1508.gtk_entry_completion_get_inline_completion$FUNC
    );
}


