// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1125() {}
    static final FunctionDescriptor gdk_drop_read_value_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_value_async$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_value_async",
        constants$1125.gdk_drop_read_value_async$FUNC
    );
    static final FunctionDescriptor gdk_drop_read_value_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_value_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_value_finish",
        constants$1125.gdk_drop_read_value_finish$FUNC
    );
    static final FunctionDescriptor gdk_input_source_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_input_source_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_input_source_get_type",
        constants$1125.gdk_input_source_get_type$FUNC
    );
    static final FunctionDescriptor gdk_device_pad_feature_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_device_pad_feature_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_device_pad_feature_get_type",
        constants$1125.gdk_device_pad_feature_get_type$FUNC
    );
    static final FunctionDescriptor gdk_device_tool_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_device_tool_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_device_tool_type_get_type",
        constants$1125.gdk_device_tool_type_get_type$FUNC
    );
    static final FunctionDescriptor gdk_drag_cancel_reason_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_drag_cancel_reason_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_drag_cancel_reason_get_type",
        constants$1125.gdk_drag_cancel_reason_get_type$FUNC
    );
}


