// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1356 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1356() {}
    static final FunctionDescriptor gtk_window_set_child$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_child$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_child",
        constants$1356.gtk_window_set_child$FUNC
    );
    static final FunctionDescriptor gtk_window_get_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_child$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_child",
        constants$1356.gtk_window_get_child$FUNC
    );
    static final FunctionDescriptor gtk_window_set_titlebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_titlebar$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_titlebar",
        constants$1356.gtk_window_set_titlebar$FUNC
    );
    static final FunctionDescriptor gtk_window_get_titlebar$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_titlebar$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_titlebar",
        constants$1356.gtk_window_get_titlebar$FUNC
    );
    static final FunctionDescriptor gtk_window_is_maximized$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_is_maximized$MH = RuntimeHelper.downcallHandle(
        "gtk_window_is_maximized",
        constants$1356.gtk_window_is_maximized$FUNC
    );
    static final FunctionDescriptor gtk_window_is_fullscreen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_is_fullscreen$MH = RuntimeHelper.downcallHandle(
        "gtk_window_is_fullscreen",
        constants$1356.gtk_window_is_fullscreen$FUNC
    );
}


