// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1219 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1219() {}
    static final FunctionDescriptor graphene_vec4_x_axis$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_vec4_x_axis$MH = RuntimeHelper.downcallHandle(
        "graphene_vec4_x_axis",
        constants$1219.graphene_vec4_x_axis$FUNC
    );
    static final FunctionDescriptor graphene_vec4_y_axis$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_vec4_y_axis$MH = RuntimeHelper.downcallHandle(
        "graphene_vec4_y_axis",
        constants$1219.graphene_vec4_y_axis$FUNC
    );
    static final FunctionDescriptor graphene_vec4_z_axis$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_vec4_z_axis$MH = RuntimeHelper.downcallHandle(
        "graphene_vec4_z_axis",
        constants$1219.graphene_vec4_z_axis$FUNC
    );
    static final FunctionDescriptor graphene_vec4_w_axis$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_vec4_w_axis$MH = RuntimeHelper.downcallHandle(
        "graphene_vec4_w_axis",
        constants$1219.graphene_vec4_w_axis$FUNC
    );
    static final FunctionDescriptor graphene_matrix_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_matrix_alloc$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_alloc",
        constants$1219.graphene_matrix_alloc$FUNC
    );
    static final FunctionDescriptor graphene_matrix_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_free$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_free",
        constants$1219.graphene_matrix_free$FUNC
    );
}


