// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1462 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1462() {}
    static final FunctionDescriptor gtk_center_layout_get_start_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_center_layout_get_start_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_center_layout_get_start_widget",
        constants$1462.gtk_center_layout_get_start_widget$FUNC
    );
    static final FunctionDescriptor gtk_center_layout_set_center_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_center_layout_set_center_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_center_layout_set_center_widget",
        constants$1462.gtk_center_layout_set_center_widget$FUNC
    );
    static final FunctionDescriptor gtk_center_layout_get_center_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_center_layout_get_center_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_center_layout_get_center_widget",
        constants$1462.gtk_center_layout_get_center_widget$FUNC
    );
    static final FunctionDescriptor gtk_center_layout_set_end_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_center_layout_set_end_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_center_layout_set_end_widget",
        constants$1462.gtk_center_layout_set_end_widget$FUNC
    );
    static final FunctionDescriptor gtk_center_layout_get_end_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_center_layout_get_end_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_center_layout_get_end_widget",
        constants$1462.gtk_center_layout_get_end_widget$FUNC
    );
    static final FunctionDescriptor gtk_toggle_button_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_toggle_button_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_button_get_type",
        constants$1462.gtk_toggle_button_get_type$FUNC
    );
}


