// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1492 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1492() {}
    static final FunctionDescriptor gtk_editable_get_selection_bounds$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_editable_get_selection_bounds$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_get_selection_bounds",
        constants$1492.gtk_editable_get_selection_bounds$FUNC
    );
    static final FunctionDescriptor gtk_editable_delete_selection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_editable_delete_selection$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_delete_selection",
        constants$1492.gtk_editable_delete_selection$FUNC
    );
    static final FunctionDescriptor gtk_editable_select_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_editable_select_region$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_select_region",
        constants$1492.gtk_editable_select_region$FUNC
    );
    static final FunctionDescriptor gtk_editable_set_position$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_editable_set_position$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_set_position",
        constants$1492.gtk_editable_set_position$FUNC
    );
    static final FunctionDescriptor gtk_editable_get_position$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_editable_get_position$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_get_position",
        constants$1492.gtk_editable_get_position$FUNC
    );
    static final FunctionDescriptor gtk_editable_get_editable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_editable_get_editable$MH = RuntimeHelper.downcallHandle(
        "gtk_editable_get_editable",
        constants$1492.gtk_editable_get_editable$FUNC
    );
}


