// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1318 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1318() {}
    static final FunctionDescriptor gtk_widget_mnemonic_activate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_mnemonic_activate$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_mnemonic_activate",
        constants$1318.gtk_widget_mnemonic_activate$FUNC
    );
    static final FunctionDescriptor gtk_widget_activate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_activate$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_activate",
        constants$1318.gtk_widget_activate$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_can_focus$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_can_focus$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_can_focus",
        constants$1318.gtk_widget_set_can_focus$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_can_focus$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_can_focus$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_can_focus",
        constants$1318.gtk_widget_get_can_focus$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_focusable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_focusable$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_focusable",
        constants$1318.gtk_widget_set_focusable$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_focusable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_focusable$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_focusable",
        constants$1318.gtk_widget_get_focusable$FUNC
    );
}


