// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1479 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1479() {}
    static final FunctionDescriptor gtk_column_view_column_get_header_menu$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_get_header_menu$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_get_header_menu",
        constants$1479.gtk_column_view_column_get_header_menu$FUNC
    );
    static final FunctionDescriptor gtk_column_view_column_set_fixed_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_set_fixed_width$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_set_fixed_width",
        constants$1479.gtk_column_view_column_set_fixed_width$FUNC
    );
    static final FunctionDescriptor gtk_column_view_column_get_fixed_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_get_fixed_width$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_get_fixed_width",
        constants$1479.gtk_column_view_column_get_fixed_width$FUNC
    );
    static final FunctionDescriptor gtk_column_view_column_set_resizable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_set_resizable$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_set_resizable",
        constants$1479.gtk_column_view_column_set_resizable$FUNC
    );
    static final FunctionDescriptor gtk_column_view_column_get_resizable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_get_resizable$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_get_resizable",
        constants$1479.gtk_column_view_column_get_resizable$FUNC
    );
    static final FunctionDescriptor gtk_column_view_column_set_expand$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_column_view_column_set_expand$MH = RuntimeHelper.downcallHandle(
        "gtk_column_view_column_set_expand",
        constants$1479.gtk_column_view_column_set_expand$FUNC
    );
}


