// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$970 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$970() {}
    static final FunctionDescriptor pango_attr_iterator_next$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_next$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_next",
        constants$970.pango_attr_iterator_next$FUNC
    );
    static final FunctionDescriptor pango_attr_iterator_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_copy$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_copy",
        constants$970.pango_attr_iterator_copy$FUNC
    );
    static final FunctionDescriptor pango_attr_iterator_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_destroy$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_destroy",
        constants$970.pango_attr_iterator_destroy$FUNC
    );
    static final FunctionDescriptor pango_attr_iterator_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_get$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_get",
        constants$970.pango_attr_iterator_get$FUNC
    );
    static final FunctionDescriptor pango_attr_iterator_get_font$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_get_font$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_get_font",
        constants$970.pango_attr_iterator_get_font$FUNC
    );
    static final FunctionDescriptor pango_attr_iterator_get_attrs$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_attr_iterator_get_attrs$MH = RuntimeHelper.downcallHandle(
        "pango_attr_iterator_get_attrs",
        constants$970.pango_attr_iterator_get_attrs$FUNC
    );
}


