// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1617 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1617() {}
    static final FunctionDescriptor gtk_flow_box_set_row_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_flow_box_set_row_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_set_row_spacing",
        constants$1617.gtk_flow_box_set_row_spacing$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_get_row_spacing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_get_row_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_get_row_spacing",
        constants$1617.gtk_flow_box_get_row_spacing$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_set_column_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_flow_box_set_column_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_set_column_spacing",
        constants$1617.gtk_flow_box_set_column_spacing$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_get_column_spacing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_get_column_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_get_column_spacing",
        constants$1617.gtk_flow_box_get_column_spacing$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_set_min_children_per_line$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_flow_box_set_min_children_per_line$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_set_min_children_per_line",
        constants$1617.gtk_flow_box_set_min_children_per_line$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_get_min_children_per_line$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_get_min_children_per_line$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_get_min_children_per_line",
        constants$1617.gtk_flow_box_get_min_children_per_line$FUNC
    );
}


