// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$629 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$629() {}
    static final FunctionDescriptor g_file_attribute_info_list_add$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_file_attribute_info_list_add$MH = RuntimeHelper.downcallHandle(
        "g_file_attribute_info_list_add",
        constants$629.g_file_attribute_info_list_add$FUNC
    );
    static final FunctionDescriptor g_file_enumerator_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_file_enumerator_get_type$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerator_get_type",
        constants$629.g_file_enumerator_get_type$FUNC
    );
    static final FunctionDescriptor g_file_enumerator_next_file$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_enumerator_next_file$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerator_next_file",
        constants$629.g_file_enumerator_next_file$FUNC
    );
    static final FunctionDescriptor g_file_enumerator_close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_enumerator_close$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerator_close",
        constants$629.g_file_enumerator_close$FUNC
    );
    static final FunctionDescriptor g_file_enumerator_next_files_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_enumerator_next_files_async$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerator_next_files_async",
        constants$629.g_file_enumerator_next_files_async$FUNC
    );
    static final FunctionDescriptor g_file_enumerator_next_files_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_enumerator_next_files_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerator_next_files_finish",
        constants$629.g_file_enumerator_next_files_finish$FUNC
    );
}


