// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$891 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$891() {}
    static final FunctionDescriptor hb_set_union$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_union$MH = RuntimeHelper.downcallHandle(
        "hb_set_union",
        constants$891.hb_set_union$FUNC
    );
    static final FunctionDescriptor hb_set_intersect$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_intersect$MH = RuntimeHelper.downcallHandle(
        "hb_set_intersect",
        constants$891.hb_set_intersect$FUNC
    );
    static final FunctionDescriptor hb_set_subtract$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_subtract$MH = RuntimeHelper.downcallHandle(
        "hb_set_subtract",
        constants$891.hb_set_subtract$FUNC
    );
    static final FunctionDescriptor hb_set_symmetric_difference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_symmetric_difference$MH = RuntimeHelper.downcallHandle(
        "hb_set_symmetric_difference",
        constants$891.hb_set_symmetric_difference$FUNC
    );
    static final FunctionDescriptor hb_set_get_population$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_get_population$MH = RuntimeHelper.downcallHandle(
        "hb_set_get_population",
        constants$891.hb_set_get_population$FUNC
    );
    static final FunctionDescriptor hb_set_get_min$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_get_min$MH = RuntimeHelper.downcallHandle(
        "hb_set_get_min",
        constants$891.hb_set_get_min$FUNC
    );
}


