// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$875 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$875() {}
    static final FunctionDescriptor cairo_region_translate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle cairo_region_translate$MH = RuntimeHelper.downcallHandle(
        "cairo_region_translate",
        constants$875.cairo_region_translate$FUNC
    );
    static final FunctionDescriptor cairo_region_subtract$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_subtract$MH = RuntimeHelper.downcallHandle(
        "cairo_region_subtract",
        constants$875.cairo_region_subtract$FUNC
    );
    static final FunctionDescriptor cairo_region_subtract_rectangle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_subtract_rectangle$MH = RuntimeHelper.downcallHandle(
        "cairo_region_subtract_rectangle",
        constants$875.cairo_region_subtract_rectangle$FUNC
    );
    static final FunctionDescriptor cairo_region_intersect$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_intersect$MH = RuntimeHelper.downcallHandle(
        "cairo_region_intersect",
        constants$875.cairo_region_intersect$FUNC
    );
    static final FunctionDescriptor cairo_region_intersect_rectangle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_intersect_rectangle$MH = RuntimeHelper.downcallHandle(
        "cairo_region_intersect_rectangle",
        constants$875.cairo_region_intersect_rectangle$FUNC
    );
    static final FunctionDescriptor cairo_region_union$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_union$MH = RuntimeHelper.downcallHandle(
        "cairo_region_union",
        constants$875.cairo_region_union$FUNC
    );
}


