// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*GDestroyNotify)(void* data);
 * }
 */
public interface GDestroyNotify {

    void apply(java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(GDestroyNotify fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$7.GDestroyNotify_UP$MH, fi, constants$7.GDestroyNotify$FUNC, scope);
    }
    static GDestroyNotify ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _user_data) -> {
            try {
                constants$7.GDestroyNotify_DOWN$MH.invokeExact(symbol, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


