// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _GdkMemoryTexture GdkMemoryTexture;
 * }
 */
public final class GdkMemoryTexture {

    // Suppresses default constructor, ensuring non-instantiability.
    private GdkMemoryTexture() {}
}


