// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _graphene_euler_t graphene_euler_t;
 * }
 */
public final class graphene_euler_t extends _graphene_euler_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private graphene_euler_t() {}
}


