// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*GSourceDisposeFunc)(struct _GSource* source);
 * }
 */
public interface GSourceDisposeFunc {

    void apply(java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(GSourceDisposeFunc fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$162.GSourceDisposeFunc_UP$MH, fi, constants$162.GSourceDisposeFunc$FUNC, scope);
    }
    static GSourceDisposeFunc ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _user_data) -> {
            try {
                constants$163.GSourceDisposeFunc_DOWN$MH.invokeExact(symbol, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


