// Generated by jextract

package gtk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _GtkMediaStreamClass GtkMediaStreamClass;
 * }
 */
public final class GtkMediaStreamClass extends _GtkMediaStreamClass {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkMediaStreamClass() {}
}


